## Homework 2 - Python

## 1. If statement

In [143]:
notas= read.csv("../../../data/notas.csv")  # relative path

In [144]:
notas

   誰..alumnos notas carrera
1  DIEGO      10    a001
2  GABRIEL     4    a001
3  ANDRE       7    a001
4  ANDRES     16    a002
5  FERNANDO   16    a003
6  MILAGROS   19    a002
7  OSCAR       9    a001
8  RODRIGO     1    a003
9  ALEJANDRO   7    a001
10 LORENZO    21    a001
11 ELIANE     18    a001
12 ALDAIR     15    a002
13 LUIS        0    a004
14 JAVIER     12    a001
15 ALONSO     17    a002
16 MARCO      18    a001
17 SEBASTIAN  15    a004
18 LUZCIA      0    a001
19 NAYEL      18    a004
20 JOAQUIN     4    a002
21 ILIZARBE    6    a001
22 VIVIANA    18    a004
23 LUIS       10    a004
24 ROCIO      13    a002
25 LEIDY      21    a001
26 MELISSA    16    a002
27 FERNANDO   15    a001
28 MARTIN     21    a001
29 DANIELA    17    a003
30 GONZALO     7    a001
31 SOFIA       6    a003
32 ANGEL      10    a004
33 CAMILA      1    a001
34 ROSA        3    a001
35 MARCELO    21    a002
36 JOSUE      16    a001
37 RUBEN      19    a002
38 HUGO       13    a003

### 1.1 If statement

In [145]:
nrows <- dim(notas)[1]


for (i in 1:nrows){
    
    if (notas$notas[i] >= 11){
        notas$Estado[i] <- "Ingresante"
        
    } else {
        notas$Estado[i] <- "No ingres坦"
    }
       
    
    if (notas$carrera[i] == "a001"){
        
        notas$Nombre_carrera[i] <- "Econom鱈a"
        
    } else if (notas$carrera[i] == "a002"){

        notas$Nombre_carrera[i] <- "Qu鱈mica"
        
    } else if (notas$carrera[i] == "a003") {
        
        notas$Nombre_carrera[i] <- "Filosofia"
        
    } else{
        notas$Nombre_carrera[i] <- "NA"
    }

    
}

In [146]:
notas

   誰..alumnos notas carrera Estado     Nombre_carrera
1  DIEGO      10    a001    No ingres坦 Econom鱈a
2  GABRIEL     4    a001    No ingres坦 Econom鱈a
3  ANDRE       7    a001    No ingres坦 Econom鱈a
4  ANDRES     16    a002    Ingresante Qu鱈mica
5  FERNANDO   16    a003    Ingresante Filosofia
6  MILAGROS   19    a002    Ingresante Qu鱈mica
7  OSCAR       9    a001    No ingres坦 Econom鱈a
8  RODRIGO     1    a003    No ingres坦 Filosofia
9  ALEJANDRO   7    a001    No ingres坦 Econom鱈a
10 LORENZO    21    a001    Ingresante Econom鱈a
11 ELIANE     18    a001    Ingresante Econom鱈a
12 ALDAIR     15    a002    Ingresante Qu鱈mica
13 LUIS        0    a004    No ingres坦 NA
14 JAVIER     12    a001    Ingresante Econom鱈a
15 ALONSO     17    a002    Ingresante Qu鱈mica
16 MARCO      18    a001    Ingresante Econom鱈a
17 SEBASTIAN  15    a004    Ingresante NA
18 LUZCIA      0    a001    No ingres坦 Econom鱈a
19 NAYEL      18    a004    Ingresante NA
20 JOAQUIN     4    a002    No ingres坦 Qu鱈mica
21 ILIZARBE    6    a001    No ingres坦 Econom鱈a
22 VIVIANA    18    a004    Ingresante NA
23 LUIS       10    a004    No ingres坦 NA
24 ROCIO      13    a002    Ingresante Qu鱈mica
25 LEIDY      21    a001    Ingresante Econom鱈a
26 MELISSA    16    a002    Ingresante Qu鱈mica
27 FERNANDO   15    a001    Ingresante Econom鱈a
28 MARTIN     21    a001    Ingresante Econom鱈a
29 DANIELA    17    a003    Ingresante Filosofia
30 GONZALO     7    a001    No ingres坦 Econom鱈a
31 SOFIA       6    a003    No ingres坦 Filosofia
32 ANGEL      10    a004    No ingres坦 NA
33 CAMILA      1    a001    No ingres坦 Econom鱈a
34 ROSA        3    a001    No ingres坦 Econom鱈a
35 MARCELO    21    a002    Ingresante Qu鱈mica
36 JOSUE      16    a001    Ingresante Econom鱈a
37 RUBEN      19    a002    Ingresante Qu鱈mica
38 HUGO       13    a003    Ingresante Filosofia

### 1.2 While - loop

In [147]:
i <- 1
nrows <- dim(notas)[1]

while (i <= nrows){
    
    if (notas$Estado[i] == "Ingresante" && notas$Nombre_carrera[i] == "Qu鱈mica" ){
        print(as.character(notas[,1][i]))
    }
    
    i <- i + 1
}

[1] "ANDRES"
[1] "MILAGROS"
[1] "ALDAIR"
[1] "ALONSO"
[1] "ROCIO"
[1] "MELISSA"
[1] "MARCELO"
[1] "RUBEN"

## 2.0 Loop

### 2.1 Coefficients loop

In [61]:
set.seed(756)

x1 <- runif(10000)
x2 <- runif(10000)
x3 <- runif(10000)
x4 <- runif(10000)

e <- rnorm(10000)

# Poblacional regression (Data Generating Process GDP)

Y <- 1 + 0.8*x1 + 1.2*x2 + 0.5*x3 + 1.5*x4 + e

In [71]:
sample_size <- c(10,50,100,200,500,1000,5000)
betas <- c()
for (j in sample_size){
    
    X <- cbind(matrix(1,j), x1[1:j],x2[1:j],x3[1:j],x4[1:j])
    Y1 = Y[1:j]
    beta <- solve(t(X) %*% X) %*% (t(X) %*% Y1)
    betas <- append(betas,c(beta))
}

In [72]:
betas

 [1]  2.97372031  0.43191704 -1.70202337 -0.67451093  1.96318522  1.96099542
 [7]  0.05933565  0.53661484  0.08725237  1.21145892  1.63682185  0.10900478
[13]  0.80170786  0.08285750  1.64998432  1.20612168  0.36159219  1.31524979
[19]  0.56356992  1.33745781  1.11887198  0.29917151  1.19858530  0.69368599
[25]  1.49455370  0.99117937  0.49124114  1.38875996  0.57932818  1.54404929
[31]  0.99619054  0.77475697  1.19712708  0.52395578  1.49247892

In [73]:
sample_size <- c(10,50,100,200,500,1000,5000)
beta1 <- matrix(0,7)
beta2 <- matrix(0,7)
beta3 <- matrix(0,7)
beta4 <- matrix(0,7)

In [74]:
Coefficient <- data.frame(sample_size, beta1, beta2, beta3, beta4)

In [75]:
Coefficient

  sample_size beta1 beta2 beta3 beta4
1   10        0     0     0     0
2   50        0     0     0     0
3  100        0     0     0     0
4  200        0     0     0     0
5  500        0     0     0     0
6 1000        0     0     0     0
7 5000        0     0     0     0

In [77]:
k <- 0

for (j in 1:7){
    k <- k + 1
    Coefficient[j,2] = betas[2 + (j -1)*5]
    Coefficient[j,3] = betas[3 + (j -1)*5]  
    Coefficient[j,4] = betas[4 + (j -1)*5]
    Coefficient[j,5] = betas[5 + (j -1)*5]
}

Coefficient

  sample_size beta1      beta2      beta3       beta4
1   10        0.43191704 -1.7020234 -0.67451093 1.963185
2   50        0.05933565  0.5366148  0.08725237 1.211459
3  100        0.10900478  0.8017079  0.08285750 1.649984
4  200        0.36159219  1.3152498  0.56356992 1.337458
5  500        0.29917151  1.1985853  0.69368599 1.494554
6 1000        0.49124114  1.3887600  0.57932818 1.544049
7 5000        0.77475697  1.1971271  0.52395578 1.492479

### 2.2 Production fish

In [79]:
production_fish = read.csv("../../../data/production_fish.csv" )  # relative path

In [80]:
production_fish

   year Anchoveta Concha.de.abanico Langostino Merluza  Calamar.gigante
1  2005 8628.396  13.53700           9.02100   23.27900 235.6300
2  2006 5891.838  14.71400          11.29500   25.18900 365.7290
3  2007 6084.713  19.93700          13.54800   28.35849 379.5566
4  2008 6159.387  18.79000          12.81700   26.34840 484.1621
5  2009 5828.636  24.63437          11.87740   36.77476 355.1066
6  2010 3330.413  60.00125          14.47794   25.64770 327.5719
7  2011 7000.093  92.02764          23.38448   28.54446 373.1957
8  2012 3693.871  38.93339          22.70722   21.05478 457.0727
9  2013 4754.118  89.29328          19.11137   31.18746 410.7595
10 2014 2255.453  52.26650          21.76299   30.77080 465.0076
11 2015 3616.481  14.84315          26.77221   25.64413 426.9323
12 2016 2732.734  10.09013          29.25375   25.80021 246.1247
13 2017 3165.490   4.59609          38.76007   37.14743 252.4299
14 2018 6072.888  36.53035          31.50588   34.87658 319.1465
15 2019 3381.437  53.11286          42.85764   28.97985 483.7652
16 2020 4314.558  46.99529          34.51697   19.84290 407.3848
   Atun      Caballa   Jurel      Sardina    Concha.de.abanico.1 Jurel.1
1   9.877000 25.711000  20.481000 0.16500000 1.8430800            56.16794
2  11.336000 58.245000 122.904000 0.04800000 4.0480000           136.82700
3   3.713293 26.248739  82.910307 0.00102000 4.8229906           134.88732
4   3.283711 47.694121  58.864202 0.00000000 0.8281875            80.09288
5   2.017061 51.355908  14.289041 0.00000000 1.8430723            47.07917
6   9.182845  9.729522   5.774274 0.00000000 2.8247486            10.40493
7   6.586856 20.478814  83.277943 0.05446333 0.8731300            72.95512
8   1.115060  9.978510  43.693940 0.08846000 0.7446100            72.93047
9   7.136436 26.600553   7.197624 0.00000000 2.1802522            54.45454
10  4.734540 29.576440   8.882560 0.00000000 0.6081600            46.34646
11 11.082120 15.314910   2.769796 0.16414000 0.6159100            17.53693
12 10.884490 57.675170   0.412040 0.00749000 0.5797500            12.47205
13 11.802750 23.249140   1.052910 0.00000000 0.3737000             6.88953
14 18.138975 24.610468  14.619846 0.00000000 1.5513662            14.72097
15 17.839298 19.598784  27.733432 0.00000000 1.2265210            40.79870
16  3.843680 28.408700  23.475890 0.00000000 0.6166967            48.11581
   Liza      Tollo    total_production
1   5.875600 0.430000 9030.414
2   3.166000 1.584000 6646.923
3   9.317622 2.834958 6790.849
4  14.514054 2.933360 6909.715
5  17.311344 4.057886 6394.983
6   9.706363 4.994712 3810.729
7  12.124808 5.687520 7719.284
8  17.162420 4.235380 4383.588
9  12.530821 3.945647 5418.516
10 12.248670 5.206880 2932.865
11 12.463520 7.717680 4178.338
12 15.757580 9.453130 3151.244
13 29.061740 6.692660 3577.546
14 23.326310 3.672117 6595.587
15 24.029820 1.241883 4122.621
16 14.992172 0.544585 4943.296

In [81]:
names(production_fish)

 [1] "year"                "Anchoveta"           "Concha.de.abanico"
 [4] "Langostino"          "Merluza"             "Calamar.gigante"
 [7] "Atun"                "Caballa"             "Jurel"
[10] "Sardina"             "Concha.de.abanico.1" "Jurel.1"
[13] "Liza"                "Tollo"               "total_production"

In [83]:
columns <- c('Atun', 'Jurel','Langostino','Tollo')

In [82]:
library(glue)

In [85]:
for (col in columns){
    production_fish[glue('{col}_%')]   <- (production_fish[glue('{col}')]  * 100) / production_fish$total_production
    }

In [86]:
production_fish

   year Anchoveta Concha.de.abanico Langostino Merluza  Calamar.gigante
1  2005 8628.396  13.53700           9.02100   23.27900 235.6300
2  2006 5891.838  14.71400          11.29500   25.18900 365.7290
3  2007 6084.713  19.93700          13.54800   28.35849 379.5566
4  2008 6159.387  18.79000          12.81700   26.34840 484.1621
5  2009 5828.636  24.63437          11.87740   36.77476 355.1066
6  2010 3330.413  60.00125          14.47794   25.64770 327.5719
7  2011 7000.093  92.02764          23.38448   28.54446 373.1957
8  2012 3693.871  38.93339          22.70722   21.05478 457.0727
9  2013 4754.118  89.29328          19.11137   31.18746 410.7595
10 2014 2255.453  52.26650          21.76299   30.77080 465.0076
11 2015 3616.481  14.84315          26.77221   25.64413 426.9323
12 2016 2732.734  10.09013          29.25375   25.80021 246.1247
13 2017 3165.490   4.59609          38.76007   37.14743 252.4299
14 2018 6072.888  36.53035          31.50588   34.87658 319.1465
15 2019 3381.437  53.11286          42.85764   28.97985 483.7652
16 2020 4314.558  46.99529          34.51697   19.84290 407.3848
   Atun      Caballa   Jurel      Sardina    Concha.de.abanico.1 Jurel.1
1   9.877000 25.711000  20.481000 0.16500000 1.8430800            56.16794
2  11.336000 58.245000 122.904000 0.04800000 4.0480000           136.82700
3   3.713293 26.248739  82.910307 0.00102000 4.8229906           134.88732
4   3.283711 47.694121  58.864202 0.00000000 0.8281875            80.09288
5   2.017061 51.355908  14.289041 0.00000000 1.8430723            47.07917
6   9.182845  9.729522   5.774274 0.00000000 2.8247486            10.40493
7   6.586856 20.478814  83.277943 0.05446333 0.8731300            72.95512
8   1.115060  9.978510  43.693940 0.08846000 0.7446100            72.93047
9   7.136436 26.600553   7.197624 0.00000000 2.1802522            54.45454
10  4.734540 29.576440   8.882560 0.00000000 0.6081600            46.34646
11 11.082120 15.314910   2.769796 0.16414000 0.6159100            17.53693
12 10.884490 57.675170   0.412040 0.00749000 0.5797500            12.47205
13 11.802750 23.249140   1.052910 0.00000000 0.3737000             6.88953
14 18.138975 24.610468  14.619846 0.00000000 1.5513662            14.72097
15 17.839298 19.598784  27.733432 0.00000000 1.2265210            40.79870
16  3.843680 28.408700  23.475890 0.00000000 0.6166967            48.11581
   Liza      Tollo    total_production Atun_%     Jurel_%    Langostino_%
1   5.875600 0.430000 9030.414         0.10937484 0.22680024 0.09989576
2   3.166000 1.584000 6646.923         0.17054508 1.84903601 0.16992825
3   9.317622 2.834958 6790.849         0.05468083 1.22091218 0.19950376
4  14.514054 2.933360 6909.715         0.04752310 0.85190492 0.18549246
5  17.311344 4.057886 6394.983         0.03154131 0.22344144 0.18572997
6   9.706363 4.994712 3810.729         0.24097343 0.15152675 0.37992567
7  12.124808 5.687520 7719.284         0.08532989 1.07882993 0.30293586
8  17.162420 4.235380 4383.588         0.02543715 0.99676202 0.51800534
9  12.530821 3.945647 5418.516         0.13170463 0.13283387 0.35270493
10 12.248670 5.206880 2932.865         0.16143054 0.30286290 0.74203858
11 12.463520 7.717680 4178.338         0.26522793 0.06628941 0.64073821
12 15.757580 9.453130 3151.244         0.34540293 0.01307547 0.92832379
13 29.061740 6.692660 3577.546         0.32991188 0.02943107 1.08342612
14 23.326310 3.672117 6595.587         0.27501683 0.22166102 0.47768118
15 24.029820 1.241883 4122.621         0.43271736 0.67271355 1.03957251
16 14.992172 0.544585 4943.296         0.07775541 0.47490361 0.69825827
   Tollo_%
1  0.004761687
2  0.023830575
3  0.041746742
4  0.042452694
5  0.063454207
6  0.131069716
7  0.073679378
8  0.096619026
9  0.072817863
10 0.177535616
11 0.184706921
12 0.299980875
13 0.187074035
14 0.055675361
15 0.030123626
16 0.011016638

## 3.0 Function section

In [92]:
set.seed(1246)

M <- matrix(runif(1000), ncol = 10)

In [94]:
dim(M)

[1] 100  10

In [102]:
standarize <- function(X){
    Z <- matrix(0,100,10)
    
    for (j in seq( 1, dim(Z)[2] ) ){
        n <- dim(Z)[1]
        a <- mean(X[,j])
        b <- sd(X[,j])*sqrt((n-1)/n)   # standar deviation correction 
        Z[,j] <- (X[,j]-a)/b
        
    }
    
    return(Z)
}

In [105]:
head(standarize(M))

     [,1]       [,2]       [,3]       [,4]        [,5]       [,6]
[1,]  0.5037233 -0.8760373 -1.1063498  1.28486046 -1.8703760 -1.2073542
[2,] -0.6413717 -1.2738454 -1.1693717 -1.13067241  1.5991503 -0.3033171
[3,] -1.4163004  1.6145167 -0.6493501  1.24296262  1.2223681 -1.3825882
[4,]  0.4601535  1.6150815  0.4547658  0.73528464  1.1790144  1.4179240
[5,]  0.9462944 -0.8009851  1.5144720 -1.09450954 -0.2131321  0.8916444
[6,] -1.3053284  1.7850062 -0.8530326  0.09105537 -0.6637149  0.3293939
     [,7]       [,8]          [,9]       [,10]
[1,]  0.0685061 -1.4132823481  0.6616931  1.0727753
[2,]  0.5980197  1.6483523133  0.7380919 -0.2998138
[3,]  0.8213802 -0.0006516097 -1.5227672 -1.2581251
[4,] -1.1495163 -0.0859263190 -1.1767414 -1.0484274
[5,] -0.3488425 -0.8571456418  0.7224381 -0.7924294
[6,] -0.6292838 -0.1970728568 -0.8659684 -1.4360387