In [59]:
notes <- read.csv("../../data/notas.csv")
notes

   ï..alumnos notas carrera
1  DIEGO      10    a001
2  GABRIEL     4    a001
3  ANDRE       7    a001
4  ANDRES     16    a002
5  FERNANDO   16    a003
6  MILAGROS   19    a002
7  OSCAR       9    a001
8  RODRIGO     1    a003
9  ALEJANDRO   7    a001
10 LORENZO    21    a001
11 ELIANE     18    a001
12 ALDAIR     15    a002
13 LUIS        0    a004
14 JAVIER     12    a001
15 ALONSO     17    a002
16 MARCO      18    a001
17 SEBASTIAN  15    a004
18 LUZCIA      0    a001
19 NAYEL      18    a004
20 JOAQUIN     4    a002
21 ILIZARBE    6    a001
22 VIVIANA    18    a004
23 LUIS       10    a004
24 ROCIO      13    a002
25 LEIDY      21    a001
26 MELISSA    16    a002
27 FERNANDO   15    a001
28 MARTIN     21    a001
29 DANIELA    17    a003
30 GONZALO     7    a001
31 SOFIA       6    a003
32 ANGEL      10    a004
33 CAMILA      1    a001
34 ROSA        3    a001
35 MARCELO    21    a002
36 JOSUE      16    a001
37 RUBEN      19    a002
38 HUGO       13    a003

In [60]:
notes['Condicion'] <- notes$notas

i <- 1

nrows = dim(notes)[1]

while (i <= nrows){
    
     if (notes$notas[i] >= 11){
        notes$Condicion[i] = 'Aprobo'
        }
    else if (notes$notas[i] < 11){
        notes$Condicion[i] = 'No aprobo'
    }
    i <- i + 1 
}
notes

   ï..alumnos notas carrera Condicion
1  DIEGO      10    a001    No aprobo
2  GABRIEL     4    a001    No aprobo
3  ANDRE       7    a001    No aprobo
4  ANDRES     16    a002    Aprobo
5  FERNANDO   16    a003    Aprobo
6  MILAGROS   19    a002    Aprobo
7  OSCAR       9    a001    No aprobo
8  RODRIGO     1    a003    No aprobo
9  ALEJANDRO   7    a001    No aprobo
10 LORENZO    21    a001    Aprobo
11 ELIANE     18    a001    Aprobo
12 ALDAIR     15    a002    Aprobo
13 LUIS        0    a004    No aprobo
14 JAVIER     12    a001    Aprobo
15 ALONSO     17    a002    Aprobo
16 MARCO      18    a001    Aprobo
17 SEBASTIAN  15    a004    Aprobo
18 LUZCIA      0    a001    No aprobo
19 NAYEL      18    a004    Aprobo
20 JOAQUIN     4    a002    No aprobo
21 ILIZARBE    6    a001    No aprobo
22 VIVIANA    18    a004    Aprobo
23 LUIS       10    a004    No aprobo
24 ROCIO      13    a002    Aprobo
25 LEIDY      21    a001    Aprobo
26 MELISSA    16    a002    Aprobo
27 FERNANDO   15    a001    Aprobo
28 MARTIN     21    a001    Aprobo
29 DANIELA    17    a003    Aprobo
30 GONZALO     7    a001    No aprobo
31 SOFIA       6    a003    No aprobo
32 ANGEL      10    a004    No aprobo
33 CAMILA      1    a001    No aprobo
34 ROSA        3    a001    No aprobo
35 MARCELO    21    a002    Aprobo
36 JOSUE      16    a001    Aprobo
37 RUBEN      19    a002    Aprobo
38 HUGO       13    a003    Aprobo

In [61]:
nrows <- dim(notes)[1]
i <- 1

while (i < nrows){
    
    if (notes$carrera[i] == 'a001'){
        notes$nomb_carrera[i] = 'Economía'
}
    else if (notes$carrera[i] == 'a002'){ 
             notes$nomb_carrera[i] = 'Química'
    } 
    else if (notes$carrera[i] == 'a003'){
             notes$nomb_carrera[i] = 'Filosofía'
    } 
    else {
        notes$nomb_carrera[i] = 'NA'
    }
    i <- i + 1
}

notes

   ï..alumnos notas carrera Condicion nomb_carrera
1  DIEGO      10    a001    No aprobo Economía
2  GABRIEL     4    a001    No aprobo Economía
3  ANDRE       7    a001    No aprobo Economía
4  ANDRES     16    a002    Aprobo    Química
5  FERNANDO   16    a003    Aprobo    Filosofía
6  MILAGROS   19    a002    Aprobo    Química
7  OSCAR       9    a001    No aprobo Economía
8  RODRIGO     1    a003    No aprobo Filosofía
9  ALEJANDRO   7    a001    No aprobo Economía
10 LORENZO    21    a001    Aprobo    Economía
11 ELIANE     18    a001    Aprobo    Economía
12 ALDAIR     15    a002    Aprobo    Química
13 LUIS        0    a004    No aprobo NA
14 JAVIER     12    a001    Aprobo    Economía
15 ALONSO     17    a002    Aprobo    Química
16 MARCO      18    a001    Aprobo    Economía
17 SEBASTIAN  15    a004    Aprobo    NA
18 LUZCIA      0    a001    No aprobo Economía
19 NAYEL      18    a004    Aprobo    NA
20 JOAQUIN     4    a002    No aprobo Química
21 ILIZARBE    6    a001    No aprobo Economía
22 VIVIANA    18    a004    Aprobo    NA
23 LUIS       10    a004    No aprobo NA
24 ROCIO      13    a002    Aprobo    Química
25 LEIDY      21    a001    Aprobo    Economía
26 MELISSA    16    a002    Aprobo    Química
27 FERNANDO   15    a001    Aprobo    Economía
28 MARTIN     21    a001    Aprobo    Economía
29 DANIELA    17    a003    Aprobo    Filosofía
30 GONZALO     7    a001    No aprobo Economía
31 SOFIA       6    a003    No aprobo Filosofía
32 ANGEL      10    a004    No aprobo NA
33 CAMILA      1    a001    No aprobo Economía
34 ROSA        3    a001    No aprobo Economía
35 MARCELO    21    a002    Aprobo    Química
36 JOSUE      16    a001    Aprobo    Economía
37 RUBEN      19    a002    Aprobo    Química
38 HUGO       13    a003    Aprobo    Economía

In [48]:
nrows <- dim(notes)[1]
i <- 1

while (i < nrows){
    
    if (notes$Condicion[i] == 'Aprobo' && notes$nomb_carrera[i] == 'Química'){
        print(notes$ï..alumnos[i])
    } 
   i <- i + 1
}

[1] ANDRES
36 Levels: ALDAIR ALEJANDRO ALONSO ANDRE ANDRES ANGEL  CAMILA DANIELA ... VIVIANA
[1] MILAGROS
36 Levels: ALDAIR ALEJANDRO ALONSO ANDRE ANDRES ANGEL  CAMILA DANIELA ... VIVIANA
[1] ALDAIR
36 Levels: ALDAIR ALEJANDRO ALONSO ANDRE ANDRES ANGEL  CAMILA DANIELA ... VIVIANA
[1] ALONSO
36 Levels: ALDAIR ALEJANDRO ALONSO ANDRE ANDRES ANGEL  CAMILA DANIELA ... VIVIANA
[1] ROCIO
36 Levels: ALDAIR ALEJANDRO ALONSO ANDRE ANDRES ANGEL  CAMILA DANIELA ... VIVIANA
[1] MELISSA
36 Levels: ALDAIR ALEJANDRO ALONSO ANDRE ANDRES ANGEL  CAMILA DANIELA ... VIVIANA
[1] MARCELO
36 Levels: ALDAIR ALEJANDRO ALONSO ANDRE ANDRES ANGEL  CAMILA DANIELA ... VIVIANA
[1] RUBEN
36 Levels: ALDAIR ALEJANDRO ALONSO ANDRE ANDRES ANGEL  CAMILA DANIELA ... VIVIANA

In [64]:
set.seed(654)
A1 <- runif(10000)
A1 <- round(A1,2)

In [65]:
A <- matrix(A1,nrow = 100,ncol = 10, byrow=TRUE)
print(A)

       [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
  [1,] 0.22 0.75 0.35 0.07 0.95 0.21 0.46 0.20 0.54  0.78
  [2,] 0.79 0.34 0.86 0.07 0.83 0.77 0.77 0.85 0.33  0.84
  [3,] 0.46 0.98 0.20 0.75 0.16 0.81 0.21 0.06 0.19  0.16
  [4,] 0.48 0.44 0.51 0.35 0.50 0.64 0.75 0.11 0.22  0.08
  [5,] 0.39 0.64 0.55 0.91 0.70 0.25 0.76 0.67 0.33  0.40
  [6,] 0.20 0.91 0.27 0.49 0.78 0.18 0.24 0.79 0.85  0.23
  [7,] 0.31 0.12 0.25 0.91 0.24 0.39 0.67 0.25 0.68  0.73
  [8,] 0.45 0.46 0.24 0.93 0.61 0.77 0.52 0.10 0.35  0.53
  [9,] 0.53 0.92 0.05 0.15 0.20 0.09 0.11 0.56 0.85  0.21
 [10,] 0.73 0.33 0.70 0.51 0.62 0.95 0.91 0.68 0.46  0.40
 [11,] 0.74 0.23 0.47 0.21 0.74 0.36 0.12 0.34 0.50  0.26
 [12,] 0.52 0.21 0.03 0.44 0.59 0.95 0.74 0.86 0.52  0.46
 [13,] 0.51 0.52 0.27 0.07 0.49 0.39 0.75 0.66 0.95  0.68
 [14,] 0.90 0.34 0.03 0.44 0.42 0.19 0.25 0.92 0.81  0.21
 [15,] 0.77 0.54 0.07 0.25 0.32 0.38 0.00 0.23 0.02  0.49
 [16,] 0.51 0.22 0.65 0.18 0.08 0.05 0.67 0.11 0.53  0.79
 [17,] 0.69 0.32 0.44 0.26 0.80 0.32 0.38 0.08 0.90  0.66
 [18,] 0.59 0.26 0.16 0.24 0.74 0.66 0.62 0.52 0.28  0.18
 [19,] 0.32 0.45 0.01 0.03 0.01 0.87 0.40 0.97 0.83  0.78
 [20,] 0.68 0.53 0.15 0.65 0.88 0.33 0.07 0.64 0.68  0.16
 [21,] 0.38 0.32 0.14 0.39 0.61 0.08 0.62 0.59 0.09  0.64
 [22,] 0.30 0.89 0.21 0.08 0.94 0.25 0.25 0.57 0.19  0.10
 [23,] 0.98 0.50 0.40 0.44 0.98 0.96 0.71 0.65 0.03  0.93
 [24,] 0.32 0.62 0.23 0.04 0.82 0.93 0.81 0.18 0.85  0.84
 [25,] 0.85 0.51 0.07 0.99 0.83 0.92 0.93 0.40 0.88  0.91
 [26,] 0.14 0.92 0.08 0.20 0.51 0.11 0.85 0.41 0.89  0.47
 [27,] 0.98 0.25 0.25 0.21 0.93 0.43 0.56 0.17 0.29  0.58
 [28,] 0.50 0.65 0.77 0.78 0.72 0.38 0.10 0.36 0.31  0.08
 [29,] 0.74 0.93 0.15 0.19 0.54 0.53 0.27 0.33 0.45  0.43
 [30,] 0.87 0.62 0.09 0.63 0.63 0.00 0.93 0.16 0.23  0.05
 [31,] 0.23 0.69 0.03 0.01 0.62 0.51 0.03 0.32 0.69  0.35
 [32,] 0.34 0.94 0.33 0.33 0.31 0.52 0.39 0.43 0.33  0.65
 [33,] 0.48 0.61 0.12 0.15 0.43 0.01 0.95 0.09 0.21  0.76
 [34,] 0.89 0.60 0.66 0.17 0.05 0.14 0.49 0.16 0.16  0.28
 [35,] 0.11 0.84 0.02 0.07 0.24 0.78 0.07 0.17 0.97  0.10
 [36,] 0.40 0.70 0.21 0.86 0.66 0.07 0.00 0.67 0.64  0.55
 [37,] 0.05 0.75 0.33 0.73 0.74 0.95 0.31 0.57 0.67  0.94
 [38,] 0.47 0.75 0.16 0.76 0.02 0.21 0.24 0.45 0.66  0.15
 [39,] 0.22 0.77 0.65 0.16 0.13 0.22 0.92 0.51 0.70  0.81
 [40,] 0.48 0.06 0.59 0.98 0.37 0.24 0.85 0.45 0.32  0.56
 [41,] 0.50 0.10 0.38 0.08 0.31 0.75 0.44 0.67 0.12  0.72
 [42,] 0.88 0.67 0.03 0.37 0.01 0.75 0.63 0.06 0.94  0.61
 [43,] 0.89 0.03 0.59 0.50 0.06 0.30 0.42 0.28 0.52  0.21
 [44,] 0.70 0.66 0.63 0.67 0.34 0.05 0.23 0.99 0.27  0.96
 [45,] 0.19 0.96 0.86 0.99 0.41 0.17 0.60 0.18 0.20  0.57
 [46,] 0.94 0.50 0.24 0.06 0.40 0.59 0.48 0.47 0.53  0.29
 [47,] 0.26 0.80 0.70 0.75 0.61 0.71 0.79 0.24 0.48  0.20
 [48,] 0.56 0.87 0.74 0.45 0.15 0.74 0.62 0.20 0.77  0.36
 [49,] 0.93 0.41 0.17 0.01 0.14 0.21 0.88 0.21 0.30  0.25
 [50,] 0.47 0.36 0.70 0.69 0.94 0.54 0.35 0.94 0.74  0.94
 [51,] 0.40 0.19 0.27 0.65 0.93 0.03 0.82 0.52 0.80  0.20
 [52,] 0.94 0.61 0.57 0.70 0.28 0.14 0.56 0.11 0.24  0.03
 [53,] 0.84 0.08 0.87 0.87 0.51 0.06 0.25 0.88 1.00  0.37
 [54,] 0.30 0.33 0.12 0.85 0.85 0.34 0.13 0.35 0.76  0.42
 [55,] 0.75 0.23 0.80 0.57 0.35 0.75 0.25 0.97 0.02  0.80
 [56,] 0.04 0.04 0.71 0.27 0.18 0.96 0.21 0.21 0.27  0.68
 [57,] 0.49 0.50 0.69 0.04 0.05 0.65 0.99 0.46 0.49  0.93
 [58,] 0.24 0.32 0.54 0.92 0.95 0.91 0.07 0.59 0.55  0.73
 [59,] 0.98 0.93 0.16 0.18 0.40 0.72 0.57 0.17 0.75  0.62
 [60,] 0.61 0.78 0.64 0.57 0.07 0.21 0.03 0.64 0.26  0.81
 [61,] 0.06 0.49 0.11 0.76 0.23 0.74 0.47 0.35 0.36  0.50
 [62,] 0.92 0.20 0.72 0.45 0.53 0.73 0.58 0.40 0.80  0.06
 [63,] 0.48 0.34 0.05 0.45 0.03 0.26 0.60 0.50 0.80  0.91
 [64,] 0.88 0.30 0.50 0.90 0.89 0.58 0.45 0.49 0.33  0.61
 [65,] 0.59 0.76 0.62 0.41 0.51 0.97 0.92 0.75 0.30  0.86
 [66,] 0.65 0.44 0.56 0.34 0.01 0.17 0.89 0.34 0.82  0.27
 [67,] 0.89 0.34 0.09 0.48 0.25 0.64 0.69 0.48 0.77  0.94
 [68,] 0.13 0.82 0.82 0.13 0.74 0.58 0.37 0.57 0.45  0.18
 [69,] 0.15 0.21 0.55 0.47 0.12 0.48 0.81 0.19 0.88  0.12
 [70,] 0.15 0.98 0.32 0.27 0.14 0.07 0.77 0.80 0.85  0.57
 [71,] 0.49 0.39 0.73 0.95 0.55 0.81 0.91 0.27 0.97  0.90
 [72,] 0.97 0.67 0.23 0.03 0.56 0.28 0.74 0.09 0.17  0.65
 [73,] 0.19 0.77 0.13 0.48 0.14 0.45 0.45 0.62 0.11  0.11
 [74,] 0.80 0.78 0.08 0.91 0.72 0.77 0.27 0.94 0.49  0.99
 [75,] 0.43 0.07 0.45 0.49 0.61 0.51 0.55 0.83 0.33  0.49
 [76,] 0.55 0.71 0.70 0.35 0.67 0.23 0.40 0.86 0.97  0.66
 [77,] 0.83 0.81 0.74 0.94 0.85 0.83 0.51 0.25 0.35  0.34
 [78,] 0.30 0.10 0.20 0.24 0.02 0.36 0.30 0.64 0.54  0.32
 [79,] 0.96 0.36 0.42 0.68 0.97 0.11 0.46 0.06 0.84  0.03
 [80,] 0.38 0.12 0.40 0.12 0.62 0.18 0.44 0.03 0.90  0.50
 [81,] 0.84 0.07 0.94 0.51 0.43 0.81 0.54 0.40 0.90  0.51
 [82,] 0.79 0.85 0.34 0.90 0.50 0.98 0.91 0.55 0.63  0.23
 [83,] 0.18 0.71 0.35 0.53 0.18 0.68 0.18 0.74 0.99  0.60
 [84,] 0.70 0.07 0.99 0.43 0.04 0.78 0.99 0.22 0.48  0.95
 [85,] 0.57 0.76 0.73 0.91 0.58 0.75 0.79 0.58 0.37  0.65
 [86,] 0.20 0.33 0.62 0.12 0.12 0.40 0.03 0.01 0.97  0.21
 [87,] 0.07 0.21 1.00 0.41 0.48 0.71 0.87 0.94 0.96  0.42
 [88,] 0.77 0.54 0.49 0.50 0.12 0.20 0.45 0.44 0.12  0.14
 [89,] 0.44 0.03 0.56 0.79 0.71 0.56 0.70 0.08 0.09  0.44
 [90,] 0.38 0.85 0.39 0.75 0.88 0.57 0.77 0.23 0.53  0.85
 [91,] 0.09 0.82 0.77 0.79 0.64 0.19 0.88 0.64 0.91  0.29
 [92,] 0.45 0.41 0.43 0.49 0.36 0.71 0.69 0.74 0.20  0.81
 [93,] 0.43 0.59 0.89 0.02 0.28 0.75 0.34 0.81 0.41  0.69
 [94,] 0.33 0.47 0.05 0.68 0.30 0.02 0.79 0.96 0.92  0.56
 [95,] 0.22 0.51 0.97 0.92 0.96 0.88 0.02 0.38 0.03  0.63
 [96,] 0.54 0.33 0.53 0.63 0.11 0.33 0.43 0.05 0.01  0.93
 [97,] 0.05 0.60 0.21 0.07 0.74 0.05 0.96 0.65 0.22  0.49
 [98,] 0.43 0.98 0.01 0.08 0.02 0.16 0.19 0.56 0.88  0.58
 [99,] 0.07 0.18 0.07 0.30 0.40 0.19 0.92 0.14 0.43  0.79
[100,] 0.94 0.10 0.15 0.43 0.80 0.28 0.76 0.38 0.58  0.29

In [ ]:
standarize <- function(a,b,c){
    result = (a-b)/c
if 
}