## GRUPO 3 WORKGROUP 3 PYTHON

## Exploring DataFrame

1. Obtener el nombre de todas las variables de la base de datos ("Region_Junin.xlsx")

In [1]:
from IPython.display import display, HTML

display(HTML(data="""
<style>
    div#notebook-container    { width: 75%; }
    div#menubar-container     { width: 65%; }
    div#maintoolbar-container { width: 80%; }a
</style>
"""))

In [2]:
import numpy as np
import pandas as pd
from pandas import DataFrame,Series

In [74]:
df = pd.read_excel (r'..\..\data\Region_Junin.xlsx')
df

,Unnamed: 0,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
0,0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,...,209,544,361,216,1,1,4,284,290,1
1,1,JUNIN,CIUDAD DEL CERRO,P.YANACANCHA,1,3,4,49,47,96,...,50,100,50,50,0,0,0,100,0,0
2,2,JUNIN,CIUDAD DEL CERRO,VICO,1,0,1,46,25,71,...,25,72,47,25,0,0,0,69,3,0
3,3,JUNIN,CIUDAD DEL CERRO,RANCA,0,6,6,25,19,44,...,25,50,25,25,0,0,0,25,25,0
4,4,JUNIN,CIUDAD DEL CERRO,PASCO,4,4,8,21,21,42,...,25,50,25,25,0,0,0,37,13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,192,JUNIN,CHACAPALCA,CHACAPALCA,1,0,1,71,0,71,...,0,72,72,0,0,0,0,35,39,0
193,193,JUNIN,YAULI,P.POMACOCHA,1,0,1,15,7,22,...,7,23,16,7,0,0,0,21,2,0
194,194,JUNIN,YAULI,PACHACHACA,2,0,2,20,8,28,...,8,30,22,8,0,0,0,4,26,0
195,195,JUNIN,YAULI,YAULI,2,6,8,74,38,112,...,37,103,76,44,0,0,37,14,69,0
196,196,JUNIN,YAULI,MINAS DE MOROCOCHA,9,5,14,87,25,112,...,30,126,96,30,0,0,1,118,7,0

In [25]:
df.values #mostrar valores del DataFrame

array([[0, 'JUNIN', 'CIUDAD DEL CERRO', ..., 284, 290, 1],
       [1, 'JUNIN', 'CIUDAD DEL CERRO', ..., 100, 0, 0],
       [2, 'JUNIN', 'CIUDAD DEL CERRO', ..., 69, 3, 0],
       ...,
       [194, 'JUNIN', 'YAULI', ..., 4, 26, 0],
       [195, 'JUNIN', 'YAULI', ..., 14, 69, 0],
       [196, 'JUNIN', 'YAULI', ..., 118, 7, 0]], dtype=object)

In [26]:
df.columns #mostrar nombres de las columnas del DataFrame

Index(['Unnamed: 0', 'Region', 'District', 'Place', '4_6_years_men',
       '4_6_years_women', '4_6_years_total', '6_14_years_men',
       '6_14_years_women', '6_14_years_total', 'man_read', 'women_read',
       'total_read', 'men_not_read', 'women_not_read', 'total_not_read',
       'man_write', 'women_write', 'total_write', 'men_not_write',
       'women_not_write', 'total_not_write', 'instruction_men',
       'instruction_women', 'instruction_total', 'no_instruction_men',
       'no_instruction_women', 'no_instruction_total', 'finished_instr_men',
       'finished_instr_women', 'finished_instr_total',
       'not_finished_instr_men', 'not_finished_instr_women',
       'not_finished_instr_total', 'peruvian_men', 'peruvian_women',
       'foreign_men', 'foreign_women', 'whites', 'natives', 'mestizos',
       'blacks'],
      dtype='object')

2. Mostrar el tipo de variables (type) así como presentar los principales estadísticos.

In [75]:
df.info()  #Mostrar el tipo de variables (type)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 197 entries, 0 to 196
Data columns (total 42 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                197 non-null    int64
 1   Region                    197 non-null    object
 2   District                  197 non-null    object
 3   Place                     197 non-null    object
 4   4_6_years_men             197 non-null    int64
 5   4_6_years_women           197 non-null    int64
 6   4_6_years_total           197 non-null    int64
 7   6_14_years_men            197 non-null    int64
 8   6_14_years_women          197 non-null    int64
 9   6_14_years_total          197 non-null    int64
 10  man_read                  197 non-null    int64
 11  women_read                197 non-null    int64
 12  total_read                197 non-null    int64
 13  men_not_read              197 non-null    int64
 14  women_not_read            197 non-null    int64
 15  total_not_read            197 non-null    int64
 16  man_write                 197 non-null    int64
 17  women_write               197 non-null    int64
 18  total_write               197 non-null    int64
 19  men_not_write             197 non-null    int64
 20  women_not_write           197 non-null    int64
 21  total_not_write           197 non-null    int64
 22  instruction_men           197 non-null    int64
 23  instruction_women         197 non-null    int64
 24  instruction_total         197 non-null    int64
 25  no_instruction_men        197 non-null    int64
 26  no_instruction_women      197 non-null    int64
 27  no_instruction_total      197 non-null    int64
 28  finished_instr_men        197 non-null    int64
 29  finished_instr_women      197 non-null    int64
 30  finished_instr_total      197 non-null    int64
 31  not_finished_instr_men    197 non-null    int64
 32  not_finished_instr_women  197 non-null    int64
 33  not_finished_instr_total  197 non-null    int64
 34  peruvian_men              197 non-null    int64
 35  peruvian_women            197 non-null    int64
 36  foreign_men               197 non-null    int64
 37  foreign_women             197 non-null    int64
 38  whites                    197 non-null    int64
 39  natives                   197 non-null    int64
 40  mestizos                  197 non-null    int64
 41  blacks                    197 non-null    int64
dtypes: int64(39), object(3)
memory usage: 64.8+ KB

In [24]:
df.describe() #Mostrar principales estadísticos

,Unnamed: 0,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,man_read,women_read,total_read,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
count,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,...,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000
mean,98.000000,16.979695,15.345178,32.324873,79.005076,62.482234,141.538071,34.654822,11.705584,46.360406,...,79.238579,172.675127,95.918782,77.664975,0.030457,0.010152,9.893401,110.558376,52.583756,0.776650
std,57.013156,22.571419,21.618979,43.489455,99.837291,90.879972,188.535210,51.091581,34.676708,83.291516,...,111.799104,220.657751,120.177520,110.539722,0.265511,0.100501,39.677190,131.094774,123.120065,7.584952
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,49.000000,4.000000,4.000000,8.000000,25.000000,19.000000,42.000000,2.000000,0.000000,2.000000,...,25.000000,50.000000,31.000000,25.000000,0.000000,0.000000,0.000000,40.000000,0.000000,0.000000
50%,98.000000,10.000000,9.000000,20.000000,55.000000,41.000000,91.000000,21.000000,0.000000,23.000000,...,50.000000,108.000000,65.000000,50.000000,0.000000,0.000000,0.000000,73.000000,3.000000,0.000000
75%,147.000000,20.000000,18.000000,39.000000,88.000000,73.000000,160.000000,42.000000,7.000000,50.000000,...,94.000000,197.000000,103.000000,91.000000,0.000000,0.000000,0.000000,143.000000,48.000000,0.000000
max,196.000000,184.000000,184.000000,368.000000,950.000000,957.000000,1907.000000,317.000000,225.000000,542.000000,...,1089.000000,2164.000000,1132.000000,1141.000000,3.000000,1.000000,348.000000,1367.000000,808.000000,92.000000

3. Verifique si las columnas presentan missing values

In [30]:
df.isnull().sum() #no hay ninguna columna que presente valores nulos (missing values)

Unnamed: 0                  0
Region                      0
District                    0
Place                       0
4_6_years_men               0
4_6_years_women             0
4_6_years_total             0
6_14_years_men              0
6_14_years_women            0
6_14_years_total            0
man_read                    0
women_read                  0
total_read                  0
men_not_read                0
women_not_read              0
total_not_read              0
man_write                   0
women_write                 0
total_write                 0
men_not_write               0
women_not_write             0
total_not_write             0
instruction_men             0
instruction_women           0
instruction_total           0
no_instruction_men          0
no_instruction_women        0
no_instruction_total        0
finished_instr_men          0
finished_instr_women        0
finished_instr_total        0
not_finished_instr_men      0
not_finished_instr_women    0
not_finished_instr_total    0
peruvian_men                0
peruvian_women              0
foreign_men                 0
foreign_women               0
whites                      0
natives                     0
mestizos                    0
blacks                      0
dtype: int64

In [202]:
df.all() #todos los que dicen false presentan valores iguales a 0 en sus columnas, los que dicen true no tienen ningun valor igual a cero

Unnamed: 0                    False
Region                         True
District                       True
comunidad                      True
4_6_years_men                 False
4_6_years_women               False
4_6_years_total               False
6_14_years_men                False
6_14_years_women              False
6_14_years_total               True
man_read                      False
women_read                    False
total_read                    False
nlee_hombre                   False
nlee_mujer                    False
ntotal_lee                    False
man_write                     False
women_write                   False
total_write                   False
nesc_hombre                   False
nesc_mujer                    False
nesc_total                     True
instruction_men               False
instruction_women             False
instruction_total             False
no_instruction_men            False
no_instruction_women          False
no_instruction_total           True
finished_instr_men            False
finished_instr_women          False
finished_instr_total          False
not_finished_instr_men        False
not_finished_instr_women      False
not_finished_instr_total      False
peruvian_men                  False
peruvian_women                False
foreign_men                   False
foreign_women                 False
whites                        False
natives                       False
mestizos                      False
blacks                        False
mujeres_noescriben_nileen     False
hombres_noescriben_nileen     False
total_raza                     True
%nativos                      False
%mujeres_noescriben_nileen    False
%hombres_noescriben_nileen    False
dtype: bool

4. Cambie el nombre de las siguientes variables:
Place : comunidad, 
man__not_read: nlee_hombre,
woman_not_read: nlee_hombre,
total_not_read: ntotal_lee,
man_not_write: nesc_hombre,
woman_not_write: nesc_hombre,
total_not_write: nesc_total,

In [76]:
df.rename(columns = {'Place':'comunidad', 'men_not_read':'nlee_hombre', 'women_not_read':'nlee_mujer', 'total_not_read':'ntotal_lee', 'men_not_write':'nesc_hombre', 'women_not_write':'nesc_mujer', 'total_not_write':'nesc_total' }, inplace = True)
df.head(5)

,Unnamed: 0,Region,District,comunidad,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
0,0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,...,209,544,361,216,1,1,4,284,290,1
1,1,JUNIN,CIUDAD DEL CERRO,P.YANACANCHA,1,3,4,49,47,96,...,50,100,50,50,0,0,0,100,0,0
2,2,JUNIN,CIUDAD DEL CERRO,VICO,1,0,1,46,25,71,...,25,72,47,25,0,0,0,69,3,0
3,3,JUNIN,CIUDAD DEL CERRO,RANCA,0,6,6,25,19,44,...,25,50,25,25,0,0,0,25,25,0
4,4,JUNIN,CIUDAD DEL CERRO,PASCO,4,4,8,21,21,42,...,25,50,25,25,0,0,0,37,13,0

6. Muestre los valores únicos de las siguientes variables (comunidad)

In [77]:
df.comunidad.unique() #valores únicos de la variable comunidad

array(['C.CIUDAD DEL CERRO', 'P.YANACANCHA', 'VICO', 'RANCA', 'PASCO',
       'QUIRLACOCHA', 'CAJAMARQUILLA', 'CAICO', 'ROCO', 'C.SACRA FAMILIA',
       'P.QUINUA', 'H.PARIAHUANCA', 'P.SULLUMARCA', 'H.SAN ANDRÉS',
       'P.HUALLAY', 'C.HUAYCHAO', 'COCHAMARCA', 'P.CHACAYÁN',
       'VILCABAMBA', 'CUCHES', 'CHANGO', 'MITO', 'ANTAPIRCA', 'P.CAYNA',
       'A. COLPAS', 'P.YACAS', 'C.MASQUIN', 'P.YAMOR', 'PÁUCAR', 'TANGOR',
       'QUIO', 'CAURY', 'CHUCCHUC', 'COQUIN', 'A.YAPOC', 'P.YANAHUANCA',
       'HUAYLACIRCA', 'HUARANTAMBO', 'ANDUCHACA', 'VILLO', 'MICHIVILCA',
       'PILLAO', 'YACÁN', 'TÁPUC', 'CHAUPIMARCA', 'P.OXAPAMPA', 'P.JAUJA',
       'A.CHUNÁN', 'C.PACAPACHA', 'HUANCAS', 'A.HUERTAS', 'PACA', 'MASMA',
       'ATAURA', 'HUALÁ', 'JULCÁN', 'P.RICRÁN', 'A.PAUCÁN', 'P.APATA',
       'HUAMALÍ', 'A.SAN LORENZO', 'PACUCHO', 'P.ORCOTUNA', 'A.VICSO',
       'TISTES', 'P.HUARIPAMPA', 'A.PARCO', 'PACCHA', 'CANCHAPUNCO',
       'C.ULLUSCA', 'CANCHAS', 'P.MUQUIYAUYO', 'MUQUI', 'P.ACOLLA',
       'MARCO', 'TRAGADERO', 'CHOCÓN', 'ACAYA', 'YAUJAILLO', 'CURICACA',
       'P.CINCOS', 'C.LLACUARI', 'P.HUANCARÍ', 'C.CHALHUAS', 'ARAMACHAY',
       'P.MITO', 'A.CHAMBARÁ', 'C.QUICHA', 'HUACHAC', 'A.ACO',
       'P.LLOCLLAPAMPA', 'VISCAS ESPERANZA', 'CONCHAILLO', 'MATA-CHICO',
       'MATA-GRANDE', 'P.CONCEPCIÓN', 'SANTA ROSA DE OCOPA', 'HUANTAR',
       'A.ALAYO', 'C.SAN ANTONIO DE CARICANCHO', 'SANTO DOMINGO',
       'P.CÓMAS', 'C.CHUPA', 'COCHAS', 'P.MATAHUASI', 'P.HUANCAYO',
       'CAJAS', 'P.CHUPACA', 'A.ISCOS', 'ANTAPAMPA', 'HUAUSCA GRANDE',
       'SAN JUAN DE TARPA', 'YANACANCHA', 'COPCA', 'HUAYAN', 'HUAMANCACA',
       'PILCOMAYO', 'AHUAC', 'ACAC', 'P.SAN GERÓNIMO', 'HUALHUAS',
       'SAN PEDRO DE SAÑO', 'QUICHUAY', 'CASACANCHA', 'A.INGENIO',
       'P.SANTA CRUZ DE QUILCAY', 'RANGRA', 'P.SAPALLANGA', 'A.LA PUNTA',
       'P.PUCARÁ', 'C.PATALÁ', 'MARCAVALLE', 'COCHARCAS', 'P.CHONGOS',
       'C.TURPAC Y TINYARI', 'SOCOS', 'PUMPUNGA', 'CHUPURO',
       'CARHUAPACHA', 'A.HUAMANCACA', 'P.SICAYA', 'A.HUANCHAC',
       'C.CACHICAMARCA', 'P.COLCA', 'A.CHACAPAMPA', 'HUASICANCHA',
       'CUCHO', 'CHILIAY', 'POTACA', 'LARIA', 'CHONGOS ALTO',
       'P.HUAYUCACHI', 'HUAMANMARCA', 'VIQUES', 'CACAS', 'HUARAPUQUIO',
       'CULLHUAS', 'RETAMA', 'PACHA', 'P.TARMA', 'MACO', 'MULLUERO',
       'ANDAMARCA', 'CHANCHA', 'TARMATAMBO', 'P.JUNÍN', 'HUASAHUASY',
       'PARI', 'YANEC', 'CHUPÁN', 'ACONCOCHA', 'ONDORES', 'P.ACOBAMBA',
       'PICOY', 'C.HUARACAYO', 'A.PALCA', 'C.HUAILAHUICHÁN',
       'P.PALCAMAYO', 'P.OROYA', 'HUAYNACANCHA', 'HUAYHUAY',
       'P.CARHUAMAYO', 'ULCUMAYO', 'P.SAN RAMÓN', 'LA MERCED',
       'P.VISCATÁN', 'PAN DE AZÚCAR', 'SUITUCANCHA', 'CHACAPALCA',
       'P.POMACOCHA', 'PACHACHACA', 'YAULI', 'MINAS DE MOROCOCHA'],
      dtype=object)

7. Borrar las varaibles finished_instr_total, finished_instr_men y finished_instr_women

In [78]:
df.drop(['finished_instr_total', 'finished_instr_men', 'finished_instr_women'], axis=1)

,Unnamed: 0,Region,District,comunidad,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
0,0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,...,209,544,361,216,1,1,4,284,290,1
1,1,JUNIN,CIUDAD DEL CERRO,P.YANACANCHA,1,3,4,49,47,96,...,50,100,50,50,0,0,0,100,0,0
2,2,JUNIN,CIUDAD DEL CERRO,VICO,1,0,1,46,25,71,...,25,72,47,25,0,0,0,69,3,0
3,3,JUNIN,CIUDAD DEL CERRO,RANCA,0,6,6,25,19,44,...,25,50,25,25,0,0,0,25,25,0
4,4,JUNIN,CIUDAD DEL CERRO,PASCO,4,4,8,21,21,42,...,25,50,25,25,0,0,0,37,13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,192,JUNIN,CHACAPALCA,CHACAPALCA,1,0,1,71,0,71,...,0,72,72,0,0,0,0,35,39,0
193,193,JUNIN,YAULI,P.POMACOCHA,1,0,1,15,7,22,...,7,23,16,7,0,0,0,21,2,0
194,194,JUNIN,YAULI,PACHACHACA,2,0,2,20,8,28,...,8,30,22,8,0,0,0,4,26,0
195,195,JUNIN,YAULI,YAULI,2,6,8,74,38,112,...,37,103,76,44,0,0,37,14,69,0
196,196,JUNIN,YAULI,MINAS DE MOROCOCHA,9,5,14,87,25,112,...,30,126,96,30,0,0,1,118,7,0

8. Crear columnas con las siguiente información: el % de mujeres que no escriben ni leen, % de varones que no escriben ni leen y % de nativos respecto al total de la población.

In [226]:
df['totalpoblacion'] = df['peruvian_men'] + df['peruvian_women'] + df['foreign_men'] + df['foreign_women']
df[f'%mujeres_noescriben_nileen'] = (df['nlee_mujer'] + df['nesc_mujer'])/ df['totalpoblacion']
df[f'%hombres_noescriben_nileen'] = (df['nlee_hombre'] + df['nesc_hombre']) / df['totalpoblacion']
df[f'%nativos'] = df['natives'] / df['totalpoblacion']
df

,Unnamed: 0,Region,District,comunidad,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,...,natives,mestizos,blacks,mujeres_noescriben_nileen,hombres_noescriben_nileen,total_raza,%nativos,%mujeres_noescriben_nileen,%hombres_noescriben_nileen,totalpoblacion
0,0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,...,284,290,1,143.381279,204.618721,579,0.490501,0.535406,0.820380,579
1,1,JUNIN,CIUDAD DEL CERRO,P.YANACANCHA,1,3,4,49,47,96,...,100,0,0,50.675676,20.324324,100,1.000000,1.000000,0.440000,100
2,2,JUNIN,CIUDAD DEL CERRO,VICO,1,0,1,46,25,71,...,69,3,0,25.423729,22.576271,72,0.958333,0.694444,0.777778,72
3,3,JUNIN,CIUDAD DEL CERRO,RANCA,0,6,6,25,19,44,...,25,25,0,26.000000,0.000000,50,0.500000,1.000000,0.000000,50
4,4,JUNIN,CIUDAD DEL CERRO,PASCO,4,4,8,21,21,42,...,37,13,0,25.531915,22.468085,50,0.740000,1.000000,0.880000,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,192,JUNIN,CHACAPALCA,CHACAPALCA,1,0,1,71,0,71,...,35,39,0,0.000000,30.418440,74,0.486111,0.000000,1.236111,72
193,193,JUNIN,YAULI,P.POMACOCHA,1,0,1,15,7,22,...,21,2,0,7.350000,8.650000,23,0.913043,0.608696,0.913043,23
194,194,JUNIN,YAULI,PACHACHACA,2,0,2,20,8,28,...,4,26,0,7.280000,15.720000,30,0.133333,0.466667,1.100000,30
195,195,JUNIN,YAULI,YAULI,2,6,8,74,38,112,...,14,69,0,22.353659,35.646341,120,0.116667,0.425000,0.733333,120
196,196,JUNIN,YAULI,MINAS DE MOROCOCHA,9,5,14,87,25,112,...,118,7,0,30.245902,88.754098,126,0.936508,0.476190,1.428571,126

9. Crear una base de datos con la siguiente información:

    a. Quedarse con la información de los distritos de Ciudad del Cerro, Jauja, Acolla, San Gerónimo, Tarma, Oroya y Concepción

In [228]:
nuevabase = df[(df["District"] == "CIUDAD DEL CERRO")| (df["District"] == "JAUJA") | (df["District"] == "ACOLLA") | (df["District"] == "SAN GERÓNIMO") | (df["District"] == "TARMA") | (df["District"] == "OROYA") | (df["District"] == "CONCEPCIÓN")]
nuevabase

,Unnamed: 0,Region,District,comunidad,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,...,natives,mestizos,blacks,mujeres_noescriben_nileen,hombres_noescriben_nileen,total_raza,%nativos,%mujeres_noescriben_nileen,%hombres_noescriben_nileen,totalpoblacion
0,0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,...,284,290,1,143.381279,204.618721,579,0.490501,0.535406,0.820380,579
1,1,JUNIN,CIUDAD DEL CERRO,P.YANACANCHA,1,3,4,49,47,96,...,100,0,0,50.675676,20.324324,100,1.000000,1.000000,0.440000,100
2,2,JUNIN,CIUDAD DEL CERRO,VICO,1,0,1,46,25,71,...,69,3,0,25.423729,22.576271,72,0.958333,0.694444,0.777778,72
3,3,JUNIN,CIUDAD DEL CERRO,RANCA,0,6,6,25,19,44,...,25,25,0,26.000000,0.000000,50,0.500000,1.000000,0.000000,50
4,4,JUNIN,CIUDAD DEL CERRO,PASCO,4,4,8,21,21,42,...,37,13,0,25.531915,22.468085,50,0.740000,1.000000,0.880000,50
5,5,JUNIN,CIUDAD DEL CERRO,QUIRLACOCHA,6,7,13,44,43,87,...,65,35,0,46.558140,37.441860,100,0.650000,0.940000,0.750000,100
6,6,JUNIN,CIUDAD DEL CERRO,CAJAMARQUILLA,9,8,17,31,39,70,...,87,0,0,47.540230,40.459770,87,1.000000,1.080460,0.919540,87
7,7,JUNIN,CIUDAD DEL CERRO,CAICO,18,23,41,90,77,167,...,175,29,0,78.738739,74.261261,208,0.841346,0.769231,0.495192,208
8,8,JUNIN,CIUDAD DEL CERRO,ROCO,7,4,11,42,19,61,...,70,2,0,21.319444,49.680556,72,0.972222,0.611111,1.361111,72
9,9,JUNIN,CIUDAD DEL CERRO,C.SACRA FAMILIA,16,8,24,26,25,51,...,73,2,0,33.440000,41.560000,75,0.973333,0.880000,1.106667,75
10,10,JUNIN,CIUDAD DEL CERRO,P.QUINUA,8,6,14,17,19,36,...,50,0,0,25.500000,25.500000,50,1.000000,1.000000,1.000000,50
11,11,JUNIN,CIUDAD DEL CERRO,H.PARIAHUANCA,2,6,8,10,12,22,...,24,6,0,18.600000,12.400000,30,0.800000,1.200000,0.800000,30
12,12,JUNIN,CIUDAD DEL CERRO,P.SULLUMARCA,12,14,26,38,32,70,...,96,0,0,46.479167,50.520833,96,1.000000,0.958333,1.041667,96
13,13,JUNIN,CIUDAD DEL CERRO,H.SAN ANDRÉS,8,0,8,17,25,42,...,44,6,0,25.531915,22.468085,50,0.880000,1.000000,0.880000,50
47,47,JUNIN,JAUJA,P.JAUJA,69,71,140,375,327,702,...,117,662,0,217.499142,179.500858,842,0.138955,0.603325,0.559382,842
48,48,JUNIN,JAUJA,A.CHUNÁN,12,11,23,45,21,66,...,89,0,0,32.415584,29.584416,89,1.000000,0.719101,0.831461,89
49,49,JUNIN,JAUJA,C.PACAPACHA,1,7,8,24,18,42,...,50,0,0,25.555556,8.444444,50,1.000000,1.000000,0.560000,50
50,50,JUNIN,JAUJA,HUANCAS,3,2,5,29,40,69,...,74,0,0,42.600000,19.400000,74,1.000000,1.135135,0.635135,74
51,51,JUNIN,JAUJA,A.HUERTAS,22,38,60,103,87,190,...,195,55,0,114.579439,41.420561,250,0.780000,0.952000,0.524000,250
52,52,JUNIN,JAUJA,PACA,1,4,5,84,52,136,...,141,0,0,56.513761,10.486239,147,1.000000,0.794326,0.446809,141
53,53,JUNIN,JAUJA,MASMA,27,15,42,148,139,287,...,294,29,0,147.542857,85.457143,323,0.893617,0.908815,0.647416,329
54,54,JUNIN,JAUJA,ATAURA,24,22,46,74,68,142,...,104,84,0,74.523179,61.476821,188,0.553191,0.813830,0.707447,188
55,55,JUNIN,JAUJA,HUALÁ,9,9,18,57,28,85,...,99,4,0,34.461538,27.538462,103,0.961165,0.679612,0.669903,103
56,56,JUNIN,JAUJA,JULCÁN,19,11,30,106,144,250,...,178,72,0,112.627778,43.372222,250,0.712000,0.900000,0.440000,250
57,57,JUNIN,JAUJA,P.RICRÁN,36,21,57,98,93,191,...,240,8,0,112.480851,92.519149,248,0.967742,0.907258,0.862903,248
58,58,JUNIN,JAUJA,A.PAUCÁN,21,13,34,85,69,154,...,65,123,0,82.529032,57.470968,188,0.345745,0.872340,0.691489,188
74,74,JUNIN,ACOLLA,P.ACOLLA,45,38,83,160,117,277,...,333,27,0,158.493197,139.506803,360,0.925000,0.841667,0.800000,360
75,75,JUNIN,ACOLLA,MARCO,16,12,28,94,55,149,...,167,10,0,67.421384,76.578616,177,0.943503,0.757062,0.949153,177
76,76,JUNIN,ACOLLA,TRAGADERO,20,13,33,87,52,139,...,169,3,0,62.566372,40.433628,172,0.982558,0.732558,0.517442,172
77,77,JUNIN,ACOLLA,CHOCÓN,2,0,2,16,22,38,...,40,0,0,22.550000,16.450000,40,1.000000,1.100000,0.850000,40
78,78,JUNIN,ACOLLA,ACAYA,2,2,4,29,21,50,...,54,0,0,23.489362,24.510638,54,1.000000,0.851852,0.888889,54
79,79,JUNIN,ACOLLA,YAUJAILLO,11,2,13,13,4,17,...,30,0,0,6.222222,21.777778,30,1.000000,0.400000,1.400000,30
80,80,JUNIN,ACOLLA,CURICACA,8,3,11,25,10,35,...,46,0,0,13.317073,15.682927,46,1.000000,0.565217,0.934783,46
96,96,JUNIN,CONCEPCIÓN,P.CONCEPCIÓN,38,43,81,178,164,342,...,141,282,0,168.534591,134.465409,423,0.333333,0.799054,0.666667,423
97,97,JUNIN,CONCEPCIÓN,SANTA ROSA DE OCOPA,28,32,60,95,93,188,...,183,65,0,118.600000,69.400000,248,0.737903,0.971774,0.608871,248
98,98,JUNIN,CONCEPCIÓN,HUANTAR,3,0,3,47,41,88,...,90,1,0,39.709091,16.290909,91,0.989011,0.857143,0.351648,91
99,99,JUNIN,CONCEPCIÓN,A.ALAYO,3,8,11,22,29,51,...,62,0,0,37.698113,12.301887,62,1.000000,1.193548,0.451613,62
100,100,JUNIN,CONCEPCIÓN,C.SAN ANTONIO DE CARICANCHO,10,8,18,68,46,114,...,132,0,0,54.453782,50.546218,132,1.000000,0.818182,0.871212,132
101,101,JUNIN,CONCEPCIÓN,SANTO DOMINGO,16,11,27,30,41,71,...,98,0,0,52.541667,44.458333,98,1.000000,1.061224,0.897959,98
121,121,JUNIN,SAN GERÓNIMO,P.SAN GERÓNIMO,51,42,93,246,238,484,...,157,72,0,208.581776,135.418224,577,0.272097,0.792028,0.544194,577
122,122,JUNIN,SAN GERÓNIMO,HUALHUAS,20,20,40,92,90,182,...,0,0,0,109.598901,72.401099,222,0.000000,0.981982,0.653153,222
123,123,JUNIN,SAN GERÓNIMO,SAN PEDRO DE SAÑO,19,13,32,73,57,130,...,64,48,0,68.530769,37.469231,162,0.395062,0.845679,0.604938,162
124,124,JUNIN,SAN GERÓNIMO,QUICHUAY,13,19,32,62,56,118,...,26,65,0,72.537313,44.462687,150,0.173333,0.960000,0.706667,150
125,125,JUNIN,SAN GERÓNIMO,CASACANCHA,10,9,19,28,27,55,...,35,8,0,36.590164,22.409836,74,0.472973,0.972973,0.635135,74
126,126,JUNIN,SAN GERÓNIMO,A.INGENIO,18,6,24,77,75,152,...,72,47,0,78.547297,50.452703,176,0.409091,0.903409,0.664773,176
127,127,JUNIN,SAN GERÓNIMO,P.SANTA CRUZ DE QUILCAY,21,20,41,101,84,185,...,42,153,0,102.495146,102.504854,226,0.185841,0.902655,0.911504,226
128,128,JUNIN,SAN GERÓNIMO,RANGRA,7,1,8,26,12,38,...,33,0,0,13.382353,18.617647,46,0.717391,0.565217,0.847826,46
161,161,JUNIN,TARMA,P.TARMA,107,117,224,386,427,813,...,189,689,1,326.560907,235.439093,1037,0.182257,0.696239,0.525554,1037
162,162,JUNIN,TARMA,MACO,28,12,40,72,52,124,...,164,0,0,64.438356,64.561644,164,1.000000,0.780488,0.890244,164
163,163,JUNIN,TARMA,MULLUERO,11,14,25,114,73,187,...,179,33,0,86.441026,100.558974,212,0.844340,0.811321,0.985849,212
164,164,JUNIN,TARMA,ANDAMARCA,7,6,13,68,52,120,...,91,42,0,51.595238,34.404762,133,0.684211,0.759398,0.511278,133
165,165,JUNIN,TARMA,CHANCHA,17,20,37,122,77,199,...,228,8,0,97.466346,111.533654,236,0.966102,0.822034,0.940678,236
166,166,JUNIN,TARMA,TARMATAMBO,3,1,4,72,32,104,...,108,0,0,33.351064,46.648936,108,1.000000,0.611111,0.990741,108
181,181,JUNIN,OROYA,P.OROYA,11,9,20,41,35,76,...,28,53,0,19.339286,33.660714,96,0.291667,0.395833,0.729167,96
182,182,JUNIN,OROYA,HUAYNACANCHA,4,2,6,11,16,27,...,33,0,0,18.545455,15.454545,33,1.000000,1.090909,0.909091,33
183,183,JUNIN,OROYA,PACHA,2,4,6,7,3,10,...,16,0,0,7.437500,9.562500,16,1.000000,0.875000,1.125000,16
184,184,JUNIN,OROYA,HUAYHUAY,13,8,21,55,33,88,...,108,1,0,34.607143,21.392857,109,0.990826,0.623853,0.394495,109

    b. Ciudades con una cantidad de niños (4-6 años) mayor a 50 y de (6-14 años) > 70

In [232]:
nueva1= nuevabase[(nuevabase["4_6_years_total"]> 50) & (nuevabase["6_14_years_total"]> 70)]
nueva1

,Unnamed: 0,Region,District,comunidad,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,...,natives,mestizos,blacks,mujeres_noescriben_nileen,hombres_noescriben_nileen,total_raza,%nativos,%mujeres_noescriben_nileen,%hombres_noescriben_nileen,totalpoblacion
0,0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,...,284,290,1,143.381279,204.618721,579,0.490501,0.535406,0.820380,579
47,47,JUNIN,JAUJA,P.JAUJA,69,71,140,375,327,702,...,117,662,0,217.499142,179.500858,842,0.138955,0.603325,0.559382,842
51,51,JUNIN,JAUJA,A.HUERTAS,22,38,60,103,87,190,...,195,55,0,114.579439,41.420561,250,0.780000,0.952000,0.524000,250
57,57,JUNIN,JAUJA,P.RICRÁN,36,21,57,98,93,191,...,240,8,0,112.480851,92.519149,248,0.967742,0.907258,0.862903,248
74,74,JUNIN,ACOLLA,P.ACOLLA,45,38,83,160,117,277,...,333,27,0,158.493197,139.506803,360,0.925000,0.841667,0.800000,360
96,96,JUNIN,CONCEPCIÓN,P.CONCEPCIÓN,38,43,81,178,164,342,...,141,282,0,168.534591,134.465409,423,0.333333,0.799054,0.666667,423
97,97,JUNIN,CONCEPCIÓN,SANTA ROSA DE OCOPA,28,32,60,95,93,188,...,183,65,0,118.600000,69.400000,248,0.737903,0.971774,0.608871,248
121,121,JUNIN,SAN GERÓNIMO,P.SAN GERÓNIMO,51,42,93,246,238,484,...,157,72,0,208.581776,135.418224,577,0.272097,0.792028,0.544194,577
161,161,JUNIN,TARMA,P.TARMA,107,117,224,386,427,813,...,189,689,1,326.560907,235.439093,1037,0.182257,0.696239,0.525554,1037

    c. Ordenar las variables según el total de la población y cantidad de población nativa

In [233]:
nueva2= nuevabase.sort_values(["totalpoblacion","natives"], ascending = [True,True])
nueva2

,Unnamed: 0,Region,District,comunidad,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,...,natives,mestizos,blacks,mujeres_noescriben_nileen,hombres_noescriben_nileen,total_raza,%nativos,%mujeres_noescriben_nileen,%hombres_noescriben_nileen,totalpoblacion
183,183,JUNIN,OROYA,PACHA,2,4,6,7,3,10,...,16,0,0,7.437500,9.562500,16,1.000000,0.875000,1.125000,16
11,11,JUNIN,CIUDAD DEL CERRO,H.PARIAHUANCA,2,6,8,10,12,22,...,24,6,0,18.600000,12.400000,30,0.800000,1.200000,0.800000,30
79,79,JUNIN,ACOLLA,YAUJAILLO,11,2,13,13,4,17,...,30,0,0,6.222222,21.777778,30,1.000000,0.400000,1.400000,30
182,182,JUNIN,OROYA,HUAYNACANCHA,4,2,6,11,16,27,...,33,0,0,18.545455,15.454545,33,1.000000,1.090909,0.909091,33
77,77,JUNIN,ACOLLA,CHOCÓN,2,0,2,16,22,38,...,40,0,0,22.550000,16.450000,40,1.000000,1.100000,0.850000,40
128,128,JUNIN,SAN GERÓNIMO,RANGRA,7,1,8,26,12,38,...,33,0,0,13.382353,18.617647,46,0.717391,0.565217,0.847826,46
80,80,JUNIN,ACOLLA,CURICACA,8,3,11,25,10,35,...,46,0,0,13.317073,15.682927,46,1.000000,0.565217,0.934783,46
3,3,JUNIN,CIUDAD DEL CERRO,RANCA,0,6,6,25,19,44,...,25,25,0,26.000000,0.000000,50,0.500000,1.000000,0.000000,50
4,4,JUNIN,CIUDAD DEL CERRO,PASCO,4,4,8,21,21,42,...,37,13,0,25.531915,22.468085,50,0.740000,1.000000,0.880000,50
13,13,JUNIN,CIUDAD DEL CERRO,H.SAN ANDRÉS,8,0,8,17,25,42,...,44,6,0,25.531915,22.468085,50,0.880000,1.000000,0.880000,50
10,10,JUNIN,CIUDAD DEL CERRO,P.QUINUA,8,6,14,17,19,36,...,50,0,0,25.500000,25.500000,50,1.000000,1.000000,1.000000,50
49,49,JUNIN,JAUJA,C.PACAPACHA,1,7,8,24,18,42,...,50,0,0,25.555556,8.444444,50,1.000000,1.000000,0.560000,50
78,78,JUNIN,ACOLLA,ACAYA,2,2,4,29,21,50,...,54,0,0,23.489362,24.510638,54,1.000000,0.851852,0.888889,54
99,99,JUNIN,CONCEPCIÓN,A.ALAYO,3,8,11,22,29,51,...,62,0,0,37.698113,12.301887,62,1.000000,1.193548,0.451613,62
2,2,JUNIN,CIUDAD DEL CERRO,VICO,1,0,1,46,25,71,...,69,3,0,25.423729,22.576271,72,0.958333,0.694444,0.777778,72
8,8,JUNIN,CIUDAD DEL CERRO,ROCO,7,4,11,42,19,61,...,70,2,0,21.319444,49.680556,72,0.972222,0.611111,1.361111,72
125,125,JUNIN,SAN GERÓNIMO,CASACANCHA,10,9,19,28,27,55,...,35,8,0,36.590164,22.409836,74,0.472973,0.972973,0.635135,74
50,50,JUNIN,JAUJA,HUANCAS,3,2,5,29,40,69,...,74,0,0,42.600000,19.400000,74,1.000000,1.135135,0.635135,74
9,9,JUNIN,CIUDAD DEL CERRO,C.SACRA FAMILIA,16,8,24,26,25,51,...,73,2,0,33.440000,41.560000,75,0.973333,0.880000,1.106667,75
6,6,JUNIN,CIUDAD DEL CERRO,CAJAMARQUILLA,9,8,17,31,39,70,...,87,0,0,47.540230,40.459770,87,1.000000,1.080460,0.919540,87
48,48,JUNIN,JAUJA,A.CHUNÁN,12,11,23,45,21,66,...,89,0,0,32.415584,29.584416,89,1.000000,0.719101,0.831461,89
98,98,JUNIN,CONCEPCIÓN,HUANTAR,3,0,3,47,41,88,...,90,1,0,39.709091,16.290909,91,0.989011,0.857143,0.351648,91
181,181,JUNIN,OROYA,P.OROYA,11,9,20,41,35,76,...,28,53,0,19.339286,33.660714,96,0.291667,0.395833,0.729167,96
12,12,JUNIN,CIUDAD DEL CERRO,P.SULLUMARCA,12,14,26,38,32,70,...,96,0,0,46.479167,50.520833,96,1.000000,0.958333,1.041667,96
101,101,JUNIN,CONCEPCIÓN,SANTO DOMINGO,16,11,27,30,41,71,...,98,0,0,52.541667,44.458333,98,1.000000,1.061224,0.897959,98
5,5,JUNIN,CIUDAD DEL CERRO,QUIRLACOCHA,6,7,13,44,43,87,...,65,35,0,46.558140,37.441860,100,0.650000,0.940000,0.750000,100
1,1,JUNIN,CIUDAD DEL CERRO,P.YANACANCHA,1,3,4,49,47,96,...,100,0,0,50.675676,20.324324,100,1.000000,1.000000,0.440000,100
55,55,JUNIN,JAUJA,HUALÁ,9,9,18,57,28,85,...,99,4,0,34.461538,27.538462,103,0.961165,0.679612,0.669903,103
166,166,JUNIN,TARMA,TARMATAMBO,3,1,4,72,32,104,...,108,0,0,33.351064,46.648936,108,1.000000,0.611111,0.990741,108
184,184,JUNIN,OROYA,HUAYHUAY,13,8,21,55,33,88,...,108,1,0,34.607143,21.392857,109,0.990826,0.623853,0.394495,109
100,100,JUNIN,CONCEPCIÓN,C.SAN ANTONIO DE CARICANCHO,10,8,18,68,46,114,...,132,0,0,54.453782,50.546218,132,1.000000,0.818182,0.871212,132
164,164,JUNIN,TARMA,ANDAMARCA,7,6,13,68,52,120,...,91,42,0,51.595238,34.404762,133,0.684211,0.759398,0.511278,133
52,52,JUNIN,JAUJA,PACA,1,4,5,84,52,136,...,141,0,0,56.513761,10.486239,147,1.000000,0.794326,0.446809,141
124,124,JUNIN,SAN GERÓNIMO,QUICHUAY,13,19,32,62,56,118,...,26,65,0,72.537313,44.462687,150,0.173333,0.960000,0.706667,150
123,123,JUNIN,SAN GERÓNIMO,SAN PEDRO DE SAÑO,19,13,32,73,57,130,...,64,48,0,68.530769,37.469231,162,0.395062,0.845679,0.604938,162
162,162,JUNIN,TARMA,MACO,28,12,40,72,52,124,...,164,0,0,64.438356,64.561644,164,1.000000,0.780488,0.890244,164
76,76,JUNIN,ACOLLA,TRAGADERO,20,13,33,87,52,139,...,169,3,0,62.566372,40.433628,172,0.982558,0.732558,0.517442,172
126,126,JUNIN,SAN GERÓNIMO,A.INGENIO,18,6,24,77,75,152,...,72,47,0,78.547297,50.452703,176,0.409091,0.903409,0.664773,176
75,75,JUNIN,ACOLLA,MARCO,16,12,28,94,55,149,...,167,10,0,67.421384,76.578616,177,0.943503,0.757062,0.949153,177
58,58,JUNIN,JAUJA,A.PAUCÁN,21,13,34,85,69,154,...,65,123,0,82.529032,57.470968,188,0.345745,0.872340,0.691489,188
54,54,JUNIN,JAUJA,ATAURA,24,22,46,74,68,142,...,104,84,0,74.523179,61.476821,188,0.553191,0.813830,0.707447,188
7,7,JUNIN,CIUDAD DEL CERRO,CAICO,18,23,41,90,77,167,...,175,29,0,78.738739,74.261261,208,0.841346,0.769231,0.495192,208
163,163,JUNIN,TARMA,MULLUERO,11,14,25,114,73,187,...,179,33,0,86.441026,100.558974,212,0.844340,0.811321,0.985849,212
122,122,JUNIN,SAN GERÓNIMO,HUALHUAS,20,20,40,92,90,182,...,0,0,0,109.598901,72.401099,222,0.000000,0.981982,0.653153,222
127,127,JUNIN,SAN GERÓNIMO,P.SANTA CRUZ DE QUILCAY,21,20,41,101,84,185,...,42,153,0,102.495146,102.504854,226,0.185841,0.902655,0.911504,226
165,165,JUNIN,TARMA,CHANCHA,17,20,37,122,77,199,...,228,8,0,97.466346,111.533654,236,0.966102,0.822034,0.940678,236
97,97,JUNIN,CONCEPCIÓN,SANTA ROSA DE OCOPA,28,32,60,95,93,188,...,183,65,0,118.600000,69.400000,248,0.737903,0.971774,0.608871,248
57,57,JUNIN,JAUJA,P.RICRÁN,36,21,57,98,93,191,...,240,8,0,112.480851,92.519149,248,0.967742,0.907258,0.862903,248
56,56,JUNIN,JAUJA,JULCÁN,19,11,30,106,144,250,...,178,72,0,112.627778,43.372222,250,0.712000,0.900000,0.440000,250
51,51,JUNIN,JAUJA,A.HUERTAS,22,38,60,103,87,190,...,195,55,0,114.579439,41.420561,250,0.780000,0.952000,0.524000,250
53,53,JUNIN,JAUJA,MASMA,27,15,42,148,139,287,...,294,29,0,147.542857,85.457143,323,0.893617,0.908815,0.647416,329
74,74,JUNIN,ACOLLA,P.ACOLLA,45,38,83,160,117,277,...,333,27,0,158.493197,139.506803,360,0.925000,0.841667,0.800000,360
96,96,JUNIN,CONCEPCIÓN,P.CONCEPCIÓN,38,43,81,178,164,342,...,141,282,0,168.534591,134.465409,423,0.333333,0.799054,0.666667,423
121,121,JUNIN,SAN GERÓNIMO,P.SAN GERÓNIMO,51,42,93,246,238,484,...,157,72,0,208.581776,135.418224,577,0.272097,0.792028,0.544194,577
0,0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297,171,468,...,284,290,1,143.381279,204.618721,579,0.490501,0.535406,0.820380,579
47,47,JUNIN,JAUJA,P.JAUJA,69,71,140,375,327,702,...,117,662,0,217.499142,179.500858,842,0.138955,0.603325,0.559382,842
161,161,JUNIN,TARMA,P.TARMA,107,117,224,386,427,813,...,189,689,1,326.560907,235.439093,1037,0.182257,0.696239,0.525554,1037

    d. Solo quedarse con las variables trabajadas en 8, Distrito, y comunidad.

In [234]:
nueva3 = df[['%mujeres_noescriben_nileen','%hombres_noescriben_nileen','%nativos','District','comunidad']]
nueva3

,%mujeres_noescriben_nileen,%hombres_noescriben_nileen,%nativos,District,comunidad
0,0.535406,0.820380,0.490501,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO
1,1.000000,0.440000,1.000000,CIUDAD DEL CERRO,P.YANACANCHA
2,0.694444,0.777778,0.958333,CIUDAD DEL CERRO,VICO
3,1.000000,0.000000,0.500000,CIUDAD DEL CERRO,RANCA
4,1.000000,0.880000,0.740000,CIUDAD DEL CERRO,PASCO
...,...,...,...,...,...
192,0.000000,1.236111,0.486111,CHACAPALCA,CHACAPALCA
193,0.608696,0.913043,0.913043,YAULI,P.POMACOCHA
194,0.466667,1.100000,0.133333,YAULI,PACHACHACA
195,0.425000,0.733333,0.116667,YAULI,YAULI
196,0.476190,1.428571,0.936508,YAULI,MINAS DE MOROCOCHA

    e. Guardar la mitad de la información en bases diferentes (llamar a cada uno Base1 y Base 2)

In [200]:
base1 = nueva3.loc[0:97,:]
base1

,%mujeres_noescriben_nileen,%hombres_noescriben_nileen,%nativos,District,comunidad
0,0.394904,0.605096,0.490501,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO
1,0.694444,0.305556,1.000000,CIUDAD DEL CERRO,P.YANACANCHA
2,0.471698,0.528302,0.958333,CIUDAD DEL CERRO,VICO
3,1.000000,0.000000,0.500000,CIUDAD DEL CERRO,RANCA
4,0.531915,0.468085,0.740000,CIUDAD DEL CERRO,PASCO
...,...,...,...,...,...
93,0.581395,0.418605,1.000000,LLOCLLAPAMPA,CONCHAILLO
94,0.533333,0.466667,1.000000,LLOCLLAPAMPA,MATA-CHICO
95,0.388889,0.611111,1.000000,LLOCLLAPAMPA,MATA-GRANDE
96,0.545161,0.454839,0.333333,CONCEPCIÓN,P.CONCEPCIÓN
97,0.614796,0.385204,0.737903,CONCEPCIÓN,SANTA ROSA DE OCOPA

In [201]:
base2 = nueva3.loc[98:197,:]
base2

,%mujeres_noescriben_nileen,%hombres_noescriben_nileen,%nativos,District,comunidad
98,0.709091,0.290909,0.989011,CONCEPCIÓN,HUANTAR
99,0.725490,0.274510,1.000000,CONCEPCIÓN,A.ALAYO
100,0.484305,0.515695,1.000000,CONCEPCIÓN,C.SAN ANTONIO DE CARICANCHO
101,0.541667,0.458333,1.000000,CONCEPCIÓN,SANTO DOMINGO
102,0.473186,0.526814,1.000000,COCHAS,P.CÓMAS
...,...,...,...,...,...
192,0.000000,0.520468,0.472973,CHACAPALCA,CHACAPALCA
193,0.400000,0.600000,0.913043,YAULI,P.POMACOCHA
194,0.297872,0.702128,0.133333,YAULI,PACHACHACA
195,0.366906,0.633094,0.116667,YAULI,YAULI
196,0.250000,0.750000,0.936508,YAULI,MINAS DE MOROCOCHA

    f. Guardar la Base1 en formato csv y excel en la carpeta data. (Use el siguiente nombre Base1_WG(numero de grupo))

In [235]:
base1.to_csv("..\..\data\base1_WHG3.csv")
base1.to_excel("..\..\data\base1_WHG3.xlsx")

10. Crear una función que me permita extraer columnas un rango de columnas y de filas. Crear una función que me permite extraer una columna según el nombre de la variable y dos filas

In [222]:
#Función (base_datos, "nombre variable", posición fila 1, posición fila2)
def funcion(bd,var,a,b):
    m = bd.loc[a:b,var]
    return m

In [225]:
funcion(df,'comunidad',0,1)

0    C.CIUDAD DEL CERRO
1          P.YANACANCHA
Name: comunidad, dtype: object