# 1. IF STATEMENT

### Un archivo .csv llamado notas está en la carpeta data. Esta base de datos posee información de algunos postulantes universitarios a la universidad. Use if statement para crear una nueva columna e indicar si el el alumno ingreso o no (nota minima aprobatoria es 11). Luego crear un columna para colocar el nombre completo de la carrera a la que postulo el alumno (a001 : Economia, a002: quimica, a003: filosofia).

In [1]:
postulantes <- read.csv("../../data/notas.csv" )

In [2]:
postulantes

   ï..alumnos notas carrera
1  DIEGO      10    a001
2  GABRIEL     4    a001
3  ANDRE       7    a001
4  ANDRES     16    a002
5  FERNANDO   16    a003
6  MILAGROS   19    a002
7  OSCAR       9    a001
8  RODRIGO     1    a003
9  ALEJANDRO   7    a001
10 LORENZO    21    a001
11 ELIANE     18    a001
12 ALDAIR     15    a002
13 LUIS        0    a004
14 JAVIER     12    a001
15 ALONSO     17    a002
16 MARCO      18    a001
17 SEBASTIAN  15    a004
18 LUZCIA      0    a001
19 NAYEL      18    a004
20 JOAQUIN     4    a002
21 ILIZARBE    6    a001
22 VIVIANA    18    a004
23 LUIS       10    a004
24 ROCIO      13    a002
25 LEIDY      21    a001
26 MELISSA    16    a002
27 FERNANDO   15    a001
28 MARTIN     21    a001
29 DANIELA    17    a003
30 GONZALO     7    a001
31 SOFIA       6    a003
32 ANGEL      10    a004
33 CAMILA      1    a001
34 ROSA        3    a001
35 MARCELO    21    a002
36 JOSUE      16    a001
37 RUBEN      19    a002
38 HUGO       13    a003

In [3]:
names(postulantes)

[1] "ï..alumnos" "notas"      "carrera"

In [4]:
nrows <- dim(postulantes)[1]
i <- 1

while (i < nrows){
    
    if (postulantes$notas[i] < 11){
        postulantes$estado[i] = "no ingresó"
}
    else {
        postulantes$estado[i] = "ingresó"
    } 
    i <- i + 1
}

postulantes

   ï..alumnos notas carrera estado
1  DIEGO      10    a001    no ingresó
2  GABRIEL     4    a001    no ingresó
3  ANDRE       7    a001    no ingresó
4  ANDRES     16    a002    ingresó
5  FERNANDO   16    a003    ingresó
6  MILAGROS   19    a002    ingresó
7  OSCAR       9    a001    no ingresó
8  RODRIGO     1    a003    no ingresó
9  ALEJANDRO   7    a001    no ingresó
10 LORENZO    21    a001    ingresó
11 ELIANE     18    a001    ingresó
12 ALDAIR     15    a002    ingresó
13 LUIS        0    a004    no ingresó
14 JAVIER     12    a001    ingresó
15 ALONSO     17    a002    ingresó
16 MARCO      18    a001    ingresó
17 SEBASTIAN  15    a004    ingresó
18 LUZCIA      0    a001    no ingresó
19 NAYEL      18    a004    ingresó
20 JOAQUIN     4    a002    no ingresó
21 ILIZARBE    6    a001    no ingresó
22 VIVIANA    18    a004    ingresó
23 LUIS       10    a004    no ingresó
24 ROCIO      13    a002    ingresó
25 LEIDY      21    a001    ingresó
26 MELISSA    16    a002    ingresó
27 FERNANDO   15    a001    ingresó
28 MARTIN     21    a001    ingresó
29 DANIELA    17    a003    ingresó
30 GONZALO     7    a001    no ingresó
31 SOFIA       6    a003    no ingresó
32 ANGEL      10    a004    no ingresó
33 CAMILA      1    a001    no ingresó
34 ROSA        3    a001    no ingresó
35 MARCELO    21    a002    ingresó
36 JOSUE      16    a001    ingresó
37 RUBEN      19    a002    ingresó
38 HUGO       13    a003    no ingresó

In [15]:
nrows <- dim(postulantes)[1]
i <- 1

while (i < nrows){
    
    if (postulantes$carrera[i] == 'a001'){
        postulantes$nombre_carrera[i] = 'Economía'
}
    else if (postulantes$carrera[i] == 'a002'){ 
             postulantes$nombre_carrera[i] = 'Química'
    } 
    else if (postulantes$carrera[i] == 'a003'){
             postulantes$nombre_carrera[i] = 'Filosofía'
    } 
    else {
        postulantes$nombre_carrera[i] = '-'
    }
    i <- i + 1
}

postulantes

   ï..alumnos notas carrera estado     nombre_carrera
1  DIEGO      10    a001    no ingresó Economía
2  GABRIEL     4    a001    no ingresó Economía
3  ANDRE       7    a001    no ingresó Economía
4  ANDRES     16    a002    ingresó    Química
5  FERNANDO   16    a003    ingresó    Filosofía
6  MILAGROS   19    a002    ingresó    Química
7  OSCAR       9    a001    no ingresó Economía
8  RODRIGO     1    a003    no ingresó Filosofía
9  ALEJANDRO   7    a001    no ingresó Economía
10 LORENZO    21    a001    ingresó    Economía
11 ELIANE     18    a001    ingresó    Economía
12 ALDAIR     15    a002    ingresó    Química
13 LUIS        0    a004    no ingresó -
14 JAVIER     12    a001    ingresó    Economía
15 ALONSO     17    a002    ingresó    Química
16 MARCO      18    a001    ingresó    Economía
17 SEBASTIAN  15    a004    ingresó    -
18 LUZCIA      0    a001    no ingresó Economía
19 NAYEL      18    a004    ingresó    -
20 JOAQUIN     4    a002    no ingresó Química
21 ILIZARBE    6    a001    no ingresó Economía
22 VIVIANA    18    a004    ingresó    -
23 LUIS       10    a004    no ingresó -
24 ROCIO      13    a002    ingresó    Química
25 LEIDY      21    a001    ingresó    Economía
26 MELISSA    16    a002    ingresó    Química
27 FERNANDO   15    a001    ingresó    Economía
28 MARTIN     21    a001    ingresó    Economía
29 DANIELA    17    a003    ingresó    Filosofía
30 GONZALO     7    a001    no ingresó Economía
31 SOFIA       6    a003    no ingresó Filosofía
32 ANGEL      10    a004    no ingresó -
33 CAMILA      1    a001    no ingresó Economía
34 ROSA        3    a001    no ingresó Economía
35 MARCELO    21    a002    ingresó    Química
36 JOSUE      16    a001    ingresó    Economía
37 RUBEN      19    a002    ingresó    Química
38 HUGO       13    a003    no ingresó Economía

### Use un loop while para mostrar el nombre de las personas ingresantes a la carrera de quimia.

In [ ]:
nrows <- dim(postulantes)[1]
i <- 1

while (i < nrows){
    
    if (postulantes$estado[i] == 'ingresó' & postulantes$nombre_carrera[i] == 'Química'){
        print(postulantes$ï..alumnos[i])
    }
   i <- i + 1
}

# 2. Loops
### Simule un proceso generador de datos con 10 mil observaciones como se explicó en la primera práctica dirigida. Use un loop para obtener los coeficientes estimados con los siguientes tamaños de muestra (10, 50, 100,200,500,1000,5000). Guardar los coeficientes estimados en un Dataframe. Nombre las columnas del dataframe con los coeficientes estimados (i.e b1, b2, b3 ...) ; y las filas, con el tamaño de muestra (n=10 , n= 50, ... ).

In [5]:
set.seed(1998)

x1 <- runif(10000)
x2 <- runif(10000)
x3 <- runif(10000)
x4 <- runif(10000)
e <- rnorm(10000)

# Poblacional regression (Data Generating Process GDP)

Y <- 1 + 0.3*x1 + 0.75*x2 - 4.3*x3 + 3.6*x4 + e

In [6]:
# Matriz X de covariables
X <- cbind(matrix(1,10000), x1,x2,x3,x4)
X

          x1         x2         x3          x4
 [1,] 1   0.03640675 0.37256357 0.13250379  0.23294848
 [2,] 1   0.25989588 0.66238274 0.45598486  0.36929450
 [3,] 1   0.05793556 0.53266409 0.46712542  0.51915037
 [4,] 1   0.03440499 0.30397805 0.12499431  0.27923079
 [5,] 1   0.93809484 0.97559420 0.49672082  0.61074071
 [6,] 1   0.41842345 0.56971372 0.32702839  0.52054406
 [7,] 1   0.00299719 0.97626629 0.64129723  0.60959472
 [8,] 1   0.85627573 0.35534630 0.04447600  0.79422993
 [9,] 1   0.91059145 0.67108690 0.11404399  0.30377875
[10,] 1   0.43628121 0.67274943 0.86529432  0.75551561
[11,] 1   0.26695974 0.79155702 0.45353669  0.65514486
[12,] 1   0.34857195 0.66942279 0.02719647  0.95239262
[13,] 1   0.40853729 0.73941646 0.93968688  0.13283318
[14,] 1   0.24127743 0.39435041 0.70362484  0.58930565
[15,] 1   0.52519997 0.62806297 0.77800425  0.82799265
[16,] 1   0.55899174 0.34538345 0.77924063  0.49519264
[17,] 1   0.73956240 0.51892848 0.67542711  0.08328462
[18,] 1   0.36416940 0.32760531 0.91979587  0.97460312
[19,] 1   0.11767984 0.34500525 0.47644442  0.88782305
[20,] 1   0.67619314 0.74139403 0.87115937  0.28524978
[21,] 1   0.78910407 0.77404059 0.41446056  0.36416375
[22,] 1   0.32674701 0.36620992 0.73757980  0.77711186
[23,] 1   0.77968030 0.59247572 0.95642776  0.69047938
[24,] 1   0.41215341 0.92032591 0.77896553  0.52994825
[25,] 1   0.97810924 0.94752883 0.10633467  0.26514949
[26,] 1   0.09914823 0.01635267 0.39820697  0.31185029
[27,] 1   0.17419598 0.58424910 0.79081521  0.27066430
[28,] 1   0.81929564 0.19689893 0.50262432  0.15535449
[29,] 1   0.67876903 0.07263715 0.28909590  0.60305182
[30,] 1   0.92155187 0.65794177 0.94758612  0.28122795
[31,] ... ...        ...        ...         ...
[32,] 1   0.85388236 0.33191134 0.009320315 0.99880850
[33,] 1   0.65415807 0.25973256 0.820082561 0.73871126
[34,] 1   0.14412420 0.07967653 0.150035684 0.22765720
[35,] 1   0.82550531 0.81922538 0.493622006 0.69547823
[36,] 1   0.08531996 0.33972065 0.265657216 0.05427401
[37,] 1   0.13919115 0.50380177 0.497710125 0.09386058
[38,] 1   0.89015388 0.10742324 0.585816998 0.66691505
[39,] 1   0.20880238 0.60379803 0.101068594 0.68670419
[40,] 1   0.40557929 0.24860543 0.126350950 0.29388371
[41,] 1   0.20827109 0.90041410 0.953014302 0.50560477
[42,] 1   0.71112061 0.49058182 0.471123253 0.36285313
[43,] 1   0.54579329 0.92918563 0.128168797 0.54284357
[44,] 1   0.85310000 0.20066905 0.581955726 0.49365991
[45,] 1   0.47100018 0.61161080 0.739644771 0.39601847
[46,] 1   0.21217419 0.52961087 0.183387640 0.97367836
[47,] 1   0.93565707 0.05614318 0.028553123 0.45567097
[48,] 1   0.74482074 0.62865609 0.765356226 0.53921282
[49,] 1   0.49889401 0.12387592 0.618661554 0.45755226
[50,] 1   0.79262272 0.14936249 0.139989539 0.16808863
[51,] 1   0.52242647 0.58446845 0.400171955 0.92045441
[52,] 1   0.80371993 0.15789681 0.035376177 0.66466988
[53,] 1   0.28107444 0.50455979 0.981735322 0.06250702
[54,] 1   0.15532498 0.26260824 0.820934518 0.09973883
[55,] 1   0.60605424 0.10733097 0.366166862 0.13431598
[56,] 1   0.44283578 0.93820652 0.770731626 0.79329924
[57,] 1   0.29352647 0.47858962 0.314511376 0.22510355
[58,] 1   0.08439196 0.53302309 0.695747796 0.07084797
[59,] 1   0.02321129 0.31351004 0.739239793 0.59496665
[60,] 1   0.69884943 0.78149208 0.238572799 0.50942804
[61,] 1   0.59172487 0.04693254 0.824444512 0.62031712

In [7]:
library(matlib)

In [8]:
#Betas estimados de toda la muestra (n=10000)
beta <- inv(t(X) %*% X) %*% (t(X) %*% Y)
beta

     [,1]
[1,]  1.0592111
[2,]  0.2114439
[3,]  0.7457142
[4,] -4.2996533
[5,]  3.5925101

In [37]:
#Ahora aplicamos loops
num <- c(10,50,100,200,500,1000,5000)
betas <- matrix(0,5,7)
for (i in 1:length(num)){
    Xn <- X[1:num[i],]
    betaN <- inv(t(Xn) %*% Xn) %*% (t(Xn) %*% Y[1:num[i]])
    betas[,i] <- betaN
    #print(num[i])
    #print(betaN)
}
#print(betas)
#print(cbind(num,t(betas)))
matrix_betas <- as.data.frame(cbind(num,t(betas)))
names(matrix_betas) <- c("N","b1","b2","b3","b4","b5")
matrix_betas

  N    b1        b2          b3        b4        b5
1   10 0.2092023 -1.89908706 1.2053590 -4.366227 7.037588
2   50 1.0681386 -0.53963481 1.4929809 -4.277545 3.681805
3  100 1.3317266 -0.04278311 0.6650075 -4.206710 3.441560
4  200 1.2711984 -0.08526590 0.6952688 -4.407950 3.629251
5  500 0.9443223  0.19421592 0.8045178 -4.216886 3.684763
6 1000 1.1155991  0.08181033 0.8504324 -4.345200 3.589238
7 5000 1.0344720  0.25032386 0.7687266 -4.303512 3.596147

### Use la base de datos production_fish.csv para obtener el porcentaje de consumo de ciertos tipos de producción marina respecto al consumo de anchoveta. Crear esta información solo para los siguiente tipos producción marina: Atun, Jurel, Langostino, Tollo.

In [45]:
library("glue")

In [42]:
production_fish = read.csv("../../data/production_fish.csv" )

In [43]:
head(production_fish)

  year Anchoveta Concha.de.abanico Langostino Merluza  Calamar.gigante
1 2005 8628.396  13.53700           9.02100   23.27900 235.6300
2 2006 5891.838  14.71400          11.29500   25.18900 365.7290
3 2007 6084.713  19.93700          13.54800   28.35849 379.5566
4 2008 6159.387  18.79000          12.81700   26.34840 484.1621
5 2009 5828.636  24.63437          11.87740   36.77476 355.1066
6 2010 3330.413  60.00125          14.47794   25.64770 327.5719
  Atun      Caballa   Jurel      Sardina Concha.de.abanico.1 Jurel.1
1  9.877000 25.711000  20.481000 0.16500 1.8430800            56.16794
2 11.336000 58.245000 122.904000 0.04800 4.0480000           136.82700
3  3.713293 26.248739  82.910307 0.00102 4.8229906           134.88732
4  3.283711 47.694121  58.864202 0.00000 0.8281875            80.09288
5  2.017061 51.355908  14.289041 0.00000 1.8430723            47.07917
6  9.182845  9.729522   5.774274 0.00000 2.8247486            10.40493
  Liza      Tollo    total_production
1  5.875600 0.430000 9030.414
2  3.166000 1.584000 6646.923
3  9.317622 2.834958 6790.849
4 14.514054 2.933360 6909.715
5 17.311344 4.057886 6394.983
6  9.706363 4.994712 3810.729

In [44]:
names(production_fish)

 [1] "year"                "Anchoveta"           "Concha.de.abanico"
 [4] "Langostino"          "Merluza"             "Calamar.gigante"
 [7] "Atun"                "Caballa"             "Jurel"
[10] "Sardina"             "Concha.de.abanico.1" "Jurel.1"
[13] "Liza"                "Tollo"               "total_production"

In [46]:
select <- c("Atun","Jurel","Langostino","Tollo")
for (col in select){
    production_fish[glue('{col}_%')]   <- (production_fish[glue('{col}')]  * 100) / production_fish$Anchoveta
    }
head(production_fish)

  year Anchoveta Concha.de.abanico Langostino Merluza  Calamar.gigante
1 2005 8628.396  13.53700           9.02100   23.27900 235.6300
2 2006 5891.838  14.71400          11.29500   25.18900 365.7290
3 2007 6084.713  19.93700          13.54800   28.35849 379.5566
4 2008 6159.387  18.79000          12.81700   26.34840 484.1621
5 2009 5828.636  24.63437          11.87740   36.77476 355.1066
6 2010 3330.413  60.00125          14.47794   25.64770 327.5719
  Atun      Caballa   Jurel      Sardina Concha.de.abanico.1 Jurel.1
1  9.877000 25.711000  20.481000 0.16500 1.8430800            56.16794
2 11.336000 58.245000 122.904000 0.04800 4.0480000           136.82700
3  3.713293 26.248739  82.910307 0.00102 4.8229906           134.88732
4  3.283711 47.694121  58.864202 0.00000 0.8281875            80.09288
5  2.017061 51.355908  14.289041 0.00000 1.8430723            47.07917
6  9.182845  9.729522   5.774274 0.00000 2.8247486            10.40493
  Liza      Tollo    total_production Atun_%     Jurel_%   Langostino_%
1  5.875600 0.430000 9030.414         0.11447087 0.2373674 0.1045501
2  3.166000 1.584000 6646.923         0.19240176 2.0860044 0.1917059
3  9.317622 2.834958 6790.849         0.06102659 1.3626001 0.2226564
4 14.514054 2.933360 6909.715         0.05331230 0.9556828 0.2080889
5 17.311344 4.057886 6394.983         0.03460606 0.2451524 0.2037767
6  9.706363 4.994712 3810.729         0.27572691 0.1733801 0.4347190
  Tollo_%
1 0.004983545
2 0.026884650
3 0.046591488
4 0.047624223
5 0.069619813
6 0.149972749

# 3. Function:

### Function Crear una matrix aleatoria de orden 100x10. Crear un función que permita estandariza cada columna; es decir, cada observación de una columna debe restarse por su media y dividirse por la desviación estándar de la columna. Llame a esta función como standarize.

In [1]:
set.seed(756)
x1 <- sample(100)

In [2]:
Mat <- matrix(x1,nrow=100, ncol=10, byrow = T)
Mat

      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  74  71   43   13   49   84   45   70   31   59
 [2,]   5  34   50    4   46   48   21   73   20   57
 [3,]  16  24   95   67   64   41   66   72   18   30
 [4,] 100  99   92   42   80   75   11   56   89   55
 [5,]  85  39   61    1   54   22   58   19   17   36
 [6,]  25  44   65    6    9   33    8    2   60   26
 [7,]  47  27   14   83   40   53   52   51   86   12
 [8,]  77  98   68   37   63   79   78   15    3   69
 [9,]  88  32   76   28   38   87   94   23   97   90
[10,]  96   7   93   91   10   82   62   35   81   29
[11,]  74  71   43   13   49   84   45   70   31   59
[12,]   5  34   50    4   46   48   21   73   20   57
[13,]  16  24   95   67   64   41   66   72   18   30
[14,] 100  99   92   42   80   75   11   56   89   55
[15,]  85  39   61    1   54   22   58   19   17   36
[16,]  25  44   65    6    9   33    8    2   60   26
[17,]  47  27   14   83   40   53   52   51   86   12
[18,]  77  98   68   37   63   79   78   15    3   69
[19,]  88  32   76   28   38   87   94   23   97   90
[20,]  96   7   93   91   10   82   62   35   81   29
[21,]  74  71   43   13   49   84   45   70   31   59
[22,]   5  34   50    4   46   48   21   73   20   57
[23,]  16  24   95   67   64   41   66   72   18   30
[24,] 100  99   92   42   80   75   11   56   89   55
[25,]  85  39   61    1   54   22   58   19   17   36
[26,]  25  44   65    6    9   33    8    2   60   26
[27,]  47  27   14   83   40   53   52   51   86   12
[28,]  77  98   68   37   63   79   78   15    3   69
[29,]  88  32   76   28   38   87   94   23   97   90
[30,]  96   7   93   91   10   82   62   35   81   29
[31,] ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
[32,]  74  71   43   13   49   84   45   70   31   59
[33,]   5  34   50    4   46   48   21   73   20   57
[34,]  16  24   95   67   64   41   66   72   18   30
[35,] 100  99   92   42   80   75   11   56   89   55
[36,]  85  39   61    1   54   22   58   19   17   36
[37,]  25  44   65    6    9   33    8    2   60   26
[38,]  47  27   14   83   40   53   52   51   86   12
[39,]  77  98   68   37   63   79   78   15    3   69
[40,]  88  32   76   28   38   87   94   23   97   90
[41,]  96   7   93   91   10   82   62   35   81   29
[42,]  74  71   43   13   49   84   45   70   31   59
[43,]   5  34   50    4   46   48   21   73   20   57
[44,]  16  24   95   67   64   41   66   72   18   30
[45,] 100  99   92   42   80   75   11   56   89   55
[46,]  85  39   61    1   54   22   58   19   17   36
[47,]  25  44   65    6    9   33    8    2   60   26
[48,]  47  27   14   83   40   53   52   51   86   12
[49,]  77  98   68   37   63   79   78   15    3   69
[50,]  88  32   76   28   38   87   94   23   97   90
[51,]  96   7   93   91   10   82   62   35   81   29
[52,]  74  71   43   13   49   84   45   70   31   59
[53,]   5  34   50    4   46   48   21   73   20   57
[54,]  16  24   95   67   64   41   66   72   18   30
[55,] 100  99   92   42   80   75   11   56   89   55
[56,]  85  39   61    1   54   22   58   19   17   36
[57,]  25  44   65    6    9   33    8    2   60   26
[58,]  47  27   14   83   40   53   52   51   86   12
[59,]  77  98   68   37   63   79   78   15    3   69
[60,]  88  32   76   28   38   87   94   23   97   90
[61,]  96   7   93   91   10   82   62   35   81   29

In [3]:
media <- mean(Mat)
media

[1] 50.5

In [4]:
stand <- sd(Mat)
stand

[1] 28.88051

In [6]:
for(i in 1:Mat[,i] ){
        mean(Mat[i])
        }
    for(j in 1:Mat[,j] ){
        sd(Mat[j])
   }

ERROR: Error in eval(expr, envir, enclos): objeto 'i' no encontrado

In [8]:
standarize <- function(x,media,stand) {
        m1 = (x- media)/stand
    return(m1)
    }

In [9]:
standarize(1,2,3)

[1] -0.3333333